// ─────────────────────────────────────────────────────────────────────────
// Smart Family Budget — recipe bank + scheduling
//
// Recipes transcribed from the "4-Week Meal Plan Collection" (FB- codes).
// Schedulable: feeds the shared plan engine (plan-engine.ts) exactly like
// High-Protein Simple, so the day-by-day browser and apply flow honour the
// user's Duration + cooking-style (batch / daily, leftovers, serving size).
// ─────────────────────────────────────────────────────────────────────────
import {
  buildPlanMeals,
  type CuratedRecipe,
  type PlanBank,
} from './plan-engine';
import {
  type CookingPreferences,
  type ScheduledMeal,
  DEFAULT_COOKING_PREFS,
} from './high-protein-plan';

const IMG =
  'https://wcjsrhdlnmfugdjtvadj.supabase.co/storage/v1/object/public/Smart%20Family%20Budget/';

const RECIPES: Record<string, CuratedRecipe> = {
  'FB-B1': {
    name: 'Bircher Muesli with Poached Pears',
    description: 'Prep Saturday night. Pears poached in honey + cinnamon.',
    imageUrl: IMG + 'bircher_muesli_with_poached_pears.png',
    blurhash: 'LEKdYn4:cZ%L~p-oMxWB0LD%n2WE',
    cookTime: 5,
    prepTime: 5,
    servings: 4,
    calories: 470,
    ingredients: [
      { id: '1', name: 'Rolled oats', quantity: '2', unit: 'cups', category: 'pantry' },
      { id: '2', name: 'Apple juice', quantity: '2', unit: 'cups', category: 'produce' },
      { id: '3', name: 'Plain yoghurt', quantity: '1', unit: 'cup', category: 'dairy' },
      { id: '4', name: 'Apples, grated', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Honey', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: 'Mixed seeds', quantity: '4', unit: 'tbsp', category: 'pantry' },
      { id: '7', name: 'Pears, poached', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Toasted walnuts', quantity: '1', unit: 'whole', category: 'bakery' },
    ],
    instructions: [
      'Sat night: soak oats in apple juice + yoghurt + apple + honey + seeds. Refrigerate.',
      'Poach pears in simmering water + honey + cinnamon 8 min.',
      'Sun morning: stir muesli, top with pear and walnuts.',
    ],
    tags: ['Family Budget', 'Breakfast', 'Quick'],
  },
  'FB-B2': {
    name: 'Big Brekkie Board (Bacon, Eggs, Mushrooms, Toast)',
    description: 'The weekend ritual. Everything on a board — everyone helps themselves.',
    imageUrl: IMG + 'big_brekkie_board_bacon_eggs_mushrooms_toast.png',
    blurhash: 'LGJ7,Z4UJ;-m%LRibbWEyZf#Z}o#',
    cookTime: 15,
    prepTime: 5,
    servings: 4,
    calories: 540,
    ingredients: [
      { id: '1', name: 'Short-cut bacon', quantity: '6', unit: 'rashers', category: 'meat' },
      { id: '2', name: 'Free-range eggs', quantity: '4', unit: 'whole', category: 'dairy' },
      { id: '3', name: 'Button mushrooms, halved', quantity: '8', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Sourdough', quantity: '4', unit: 'slices', category: 'bakery' },
      { id: '5', name: 'Vine tomato, halved', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Tomato sauce', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '7', name: 'BBQ sauce', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Fry bacon 2–3 min per side. Fry mushrooms and tomato halves.',
      'Fry or poach eggs. Toast bread.',
      'Lay everything on a board. Serve family style.',
    ],
    tags: ['Family Budget', 'Breakfast'],
  },
  'FB-B3': {
    name: 'Banana Overnight Oats with Honey & Almonds',
    description: 'Prep 4 jars Sunday night — breakfast is grab-and-go all week.',
    imageUrl: IMG + 'banana_overnight_oats_with_honey_almonds.png',
    blurhash: 'LDJ*I,4mF49b?G~qkE0017E2m*Ri',
    cookTime: 5,
    prepTime: 5,
    servings: 4,
    calories: 480,
    ingredients: [
      { id: '1', name: 'Rolled oats', quantity: '2', unit: 'cups', category: 'pantry' },
      { id: '2', name: 'Milk or oat milk', quantity: '2', unit: 'cups', category: 'dairy' },
      { id: '3', name: 'Ripe bananas, mashed', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Plain yoghurt', quantity: '4', unit: 'tbsp', category: 'dairy' },
      { id: '5', name: 'Honey', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: 'Cinnamon', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '7', name: 'Raw almonds, chopped', quantity: '4', unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Mix oats, milk, banana, yoghurt, honey, cinnamon in 4 jars.',
      'Seal, refrigerate overnight.',
      'Morning: top with almonds. Eat from jar.',
    ],
    tags: ['Family Budget', 'Breakfast', 'Quick'],
  },
  'FB-B4': {
    name: 'Vegemite & Avocado Toast with Eggs',
    description: 'An Aussie breakfast institution. Creamy avo, salty Vegemite, runny eggs.',
    imageUrl: IMG + 'vegemite_avocado_toast_with_eggs.png',
    blurhash: 'LAHeaz~qyE%2009FM_WV0mIAMwNG',
    cookTime: 10,
    prepTime: 5,
    servings: 4,
    calories: 490,
    ingredients: [
      { id: '1', name: 'Wholegrain or sourdough bread', quantity: '8', unit: 'slices', category: 'bakery' },
      { id: '2', name: 'Ripe avocados', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Vegemite', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '4', name: 'Free-range eggs', quantity: '4', unit: 'whole', category: 'dairy' },
      { id: '5', name: 'Oil spray or olive oil', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '6', name: 'Cracked black pepper, chilli flakes', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Toast bread. Mash avocado with black pepper.',
      'Fry or poach eggs to liking.',
      'Spread Vegemite on toast, pile on avo, top with egg.',
    ],
    tags: ['Family Budget', 'Breakfast', 'Quick'],
  },
  'FB-B5': {
    name: 'Greek Yoghurt with Mixed Berries & Chia Seeds',
    description: 'No cooking. A complete breakfast in 2 minutes.',
    imageUrl: IMG + 'greek_yoghurt_with_mixed_berries_chia_seeds.png',
    blurhash: 'LWK^vl?bx[jF~pM{R*ofx[RjV@tR',
    cookTime: 3,
    prepTime: 5,
    servings: 4,
    calories: 380,
    ingredients: [
      { id: '1', name: 'Plain Greek yoghurt per serve', quantity: '0.75', unit: 'cup', category: 'dairy' },
      { id: '2', name: 'Mixed berries, fresh or frozen thawed', quantity: '0.5', unit: 'cup', category: 'frozen' },
      { id: '3', name: 'Chia seeds', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '4', name: 'Honey', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Muesli or granola', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Thaw frozen berries overnight if needed.',
      'Spoon yoghurt into bowl. Top with berries, chia, honey.',
    ],
    tags: ['Family Budget', 'Breakfast', 'Quick'],
  },
  'FB-B6': {
    name: 'Smoothie Bowls with Granola & Seasonal Fruit',
    description: 'The most Instagrammable breakfast in Australia. But actually fast and nutritious.',
    imageUrl: IMG + 'smoothie_bowls_with_granola_seasonal_fruit.png',
    blurhash: 'LFJj@*02TIt0%2xtV@xbYR?EIBRT',
    cookTime: 10,
    prepTime: 5,
    servings: 4,
    calories: 480,
    ingredients: [
      { id: '1', name: 'Frozen mixed berries', quantity: '400', unit: 'g', category: 'frozen' },
      { id: '2', name: 'Ripe bananas', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Plain yoghurt', quantity: '1', unit: 'cup', category: 'dairy' },
      { id: '4', name: 'Milk', quantity: '1', unit: 'cup', category: 'dairy' },
      { id: '5', name: 'Granola', quantity: '4', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: 'Seasonal fruit: mango, kiwi, strawberries', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Honey', quantity: '2', unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Blend frozen berries, bananas, yoghurt and milk until very thick.',
      'Pour into 4 bowls. Top with granola, fresh fruit and honey.',
    ],
    tags: ['Family Budget', 'Breakfast', 'Quick'],
  },
  'FB-B7': {
    name: 'Shakshuka for Four',
    description: 'Eggs poached in spiced tomato sauce. Most-saved weekend brunch recipe in Australia.',
    imageUrl: IMG + 'shakshuka_for_four.png',
    blurhash: 'LQHdd0?aOY%1~VtRf+WBOs%L%1WB',
    cookTime: 20,
    prepTime: 5,
    servings: 4,
    calories: 440,
    ingredients: [
      { id: '1', name: 'Free-range eggs', quantity: '4', unit: 'whole', category: 'dairy' },
      { id: '2', name: 'Tin crushed tomatoes', quantity: '400', unit: 'g', category: 'produce' },
      { id: '3', name: 'Large onion', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Garlic cloves', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Smoked paprika', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Cumin', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '7', name: 'Chilli flakes', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '8', name: 'Olive oil', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '9', name: 'Crumbled feta', quantity: '100', unit: 'g', category: 'dairy' },
      { id: '10', name: 'Fresh herbs', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Sourdough', quantity: '1', unit: 'whole', category: 'bakery' },
    ],
    instructions: [
      'Fry onion 3–4 min, add garlic and spices 1 min.',
      'Add tomatoes, simmer 4–5 min.',
      'Make wells, crack eggs in. Cover and cook 4–5 min.',
      'Scatter feta, herbs. Serve from pan with bread.',
      'Lunches',
    ],
    tags: ['Family Budget', 'Breakfast'],
  },
  'FB-L1': {
    name: 'Chicken Caesar Wrap',
    description: 'Aussie cafe classic made at home for a fraction of the cost.',
    imageUrl: IMG + 'chicken_caesar_wrap.png',
    blurhash: 'LgLNrjoIkXj[?wRjWAj[WEoLoIj]',
    cookTime: 15,
    prepTime: 5,
    servings: 4,
    calories: 580,
    ingredients: [
      { id: '1', name: 'Large wholegrain wraps', quantity: '4', unit: 'whole', category: 'bakery' },
      { id: '2', name: 'Cooked chicken breasts or rotisserie chicken, sliced', quantity: '2', unit: 'whole', category: 'meat' },
      { id: '3', name: 'Cos lettuce leaves, shredded', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Light Caesar dressing (yoghurt', quantity: '4', unit: 'tbsp', category: 'dairy' },
      { id: '5', name: 'Lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Garlic)', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Parmesan', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { id: '8', name: 'Croutons', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '9', name: 'Lemon', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Mix Caesar dressing: yoghurt, lemon, garlic.',
      'Lay wrap flat. Layer lettuce, chicken, croutons, dressing.',
      'Roll tightly, cut in half. Serve.',
    ],
    tags: ['Family Budget', 'Lunch'],
  },
  'FB-L2': {
    name: 'Tinned Salmon & Avocado Rice Paper Rolls',
    description: 'Vietnamese-style rolls. Fresh, light, no cooking required.',
    imageUrl: IMG + 'tinned_salmon_avocado_rice_paper_rolls.png',
    blurhash: 'LUIr7{?b.9oz~pj]WYt7.8RkRPWB',
    cookTime: 20,
    prepTime: 5,
    servings: 4,
    calories: 390,
    ingredients: [
      { id: '1', name: 'Rice paper rounds', quantity: '12', unit: 'whole', category: 'pantry' },
      { id: '2', name: 'Leftover curry chicken or tinned salmon', quantity: '1.5', unit: 'cups', category: 'meat' },
      { id: '3', name: 'Ripe avocado, sliced', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Shredded cos lettuce', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Cucumber julienned', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Fresh mint', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '7', name: 'Sweet chilli dipping sauce', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Soak rice paper one at a time in warm water 15 sec.',
      'Lay flat. Layer filling on lower third. Fold sides, roll up.',
      '3 rolls per person. Serve with sweet chilli.',
    ],
    tags: ['Family Budget', 'Lunch'],
  },
  'FB-L3': {
    name: 'Chicken Fried Rice',
    description: 'Australia\'s most-cooked weeknight dish — and it uses leftover rice.',
    imageUrl: IMG + 'chicken_fried_rice.png',
    blurhash: 'LSKKD,~q.8%Mt7tRxts:.8ozxDs.',
    cookTime: 15,
    prepTime: 5,
    servings: 4,
    calories: 520,
    ingredients: [
      { id: '1', name: 'Day-old cooked rice', quantity: '2', unit: 'cups', category: 'pantry' },
      { id: '2', name: 'Leftover shredded chicken', quantity: '1', unit: 'cup', category: 'meat' },
      { id: '3', name: 'Eggs, whisked', quantity: '3', unit: 'whole', category: 'dairy' },
      { id: '4', name: 'Frozen peas and corn', quantity: '1', unit: 'cup', category: 'frozen' },
      { id: '5', name: 'Spring onions', quantity: '3', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Garlic cloves, minced', quantity: '2', unit: 'whole', category: 'meat' },
      { id: '7', name: 'Soy sauce', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '8', name: 'Sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
    ],
    instructions: [
      'Heat wok on HIGH. Stir-fry garlic and spring onions 30 sec.',
      'Scramble eggs. Add cold rice and toss 3–4 min on HIGH.',
      'Add chicken, peas and corn 2 min. Toss with soy and sesame.',
    ],
    tags: ['Family Budget', 'Lunch'],
  },
  'FB-L4': {
    name: 'Lamb (or Turkey) Kofta Wraps with Tzatziki',
    description: 'Middle Eastern street food at home. Fresher and cheaper than the kebab shop.',
    imageUrl: IMG + 'lamb_kofta_wraps_with_tzatziki_tabbouleh.png',
    blurhash: 'L6JRHp00*0_M^+e,RPWA0toh4TM}',
    cookTime: 30,
    prepTime: 5,
    servings: 4,
    calories: 610,
    ingredients: [
      { id: '1', name: 'Lamb mince OR turkey mince', quantity: '500', unit: 'g', category: 'meat' },
      { id: '2', name: 'Cumin', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '3', name: 'Coriander', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '4', name: 'Cinnamon', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Garlic powder', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '6', name: 'Onion grated', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Parsley', quantity: '2', unit: 'tbsp', category: 'produce' },
      { id: '8', name: 'Large wraps or flatbreads', quantity: '4', unit: 'whole', category: 'bakery' },
      { id: '9', name: 'Tzatziki: 1 cup yoghurt', quantity: '1', unit: 'whole', category: 'dairy' },
      { id: '10', name: 'Grated cucumber', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Garlic clove', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '12', name: 'Shredded lettuce', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '13', name: 'Quick tomato tabbouleh', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Mix mince with spices, onion, parsley. Shape into 12 koftas.',
      'BBQ or pan-fry 3–4 min per side until golden.',
      'Make tzatziki. Assemble wraps with lettuce, kofta, tabbouleh, tzatziki.',
    ],
    tags: ['Family Budget', 'Lunch'],
  },
  'FB-L5': {
    name: 'Pulled Lamb Flatbread Pizzas',
    description: 'Slow-cooker lamb as flatbread pizza. Braising juices become the sauce.',
    imageUrl: IMG + 'pulled_lamb_flatbread_pizzas.png',
    blurhash: 'LNKT*:^+XTxu%NWWV@oLY8kCoJR*',
    cookTime: 20,
    prepTime: 5,
    servings: 4,
    calories: 550,
    ingredients: [
      { id: '1', name: 'Pulled lamb', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Flatbreads or large wraps', quantity: '4', unit: 'whole', category: 'bakery' },
      { id: '3', name: 'Strained lamb braising juices', quantity: '0.5', unit: 'cup', category: 'meat' },
      { id: '4', name: 'Crumbled feta', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { id: '5', name: 'Grated mozzarella', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '6', name: 'Red onion, sliced', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Fresh rocket', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Olive oil', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Preheat oven 220C.',
      'Spread braising juices over flatbreads. Top with lamb, onion, feta, mozzarella.',
      'Bake 8–10 min until edges crisp and cheese bubbles.',
      'Top with rocket and olive oil.',
    ],
    tags: ['Family Budget', 'Lunch'],
  },
  'FB-L6': {
    name: 'Nachos with Beef/Turkey Mince & Jalapeño',
    description: 'Friday-feels lunch — uses Wednesday\'s batch mince.',
    imageUrl: IMG + 'nachos_with_beef_turkey_mince_jalape_o.png',
    blurhash: 'LRKTby_2x]xa~VWXRQaxKRV[V@oe',
    cookTime: 20,
    prepTime: 5,
    servings: 4,
    calories: 640,
    ingredients: [
      { id: '1', name: 'Half the cooked bolognese mince', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Large bag corn chips', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Grated tasty cheddar', quantity: '1', unit: 'cup', category: 'pantry' },
      { id: '4', name: 'Sour cream', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { id: '5', name: 'Salsa', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '6', name: 'Guacamole', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '7', name: 'Jalapeños from jar', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Preheat oven 200C. Spread chips on tray.',
      'Warm mince. Spoon over chips. Scatter cheese.',
      'Bake 8–10 min until melted. Top with sour cream, guac, salsa.',
    ],
    tags: ['Family Budget', 'Lunch'],
  },
  'FB-L7': {
    name: 'Quinoa Tabbouleh with Chickpeas & Feta',
    description: 'Fresh, high-protein, genuinely travels well as a tiffin.',
    imageUrl: IMG + 'quinoa_tabbouleh_with_chickpeas_feta.png',
    blurhash: 'LHKT;{~qo~xu^$M{WBn$?vM{RPoL',
    cookTime: 15,
    prepTime: 5,
    servings: 4,
    calories: 480,
    ingredients: [
      { id: '1', name: 'Cooked quinoa per serve', quantity: '0.75', unit: 'cup', category: 'pantry' },
      { id: '2', name: 'Chickpeas , rinsed', quantity: '0.5', unit: 'tin', category: 'produce' },
      { id: '3', name: 'Lebanese cucumber', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Cherry tomatoes', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '5', name: 'Large handful flat-leaf parsley', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Spring onions', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Crumbled feta', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { id: '9', name: 'Olive oil', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '10', name: 'Black pepper', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Toss cooled quinoa with cucumber, tomato, parsley, spring onions.',
      'Dress with lemon juice and olive oil. Season.',
      'Top with chickpeas and feta.',
    ],
    tags: ['Family Budget', 'Lunch'],
  },
  'FB-D1': {
    name: 'Thai-Style Chicken Thigh Curry (Double Batch)',
    description: 'Cook double tonight — becomes biryani Monday and rice paper rolls Tuesday.',
    imageUrl: IMG + 'thai_style_chicken_thigh_curry.png',
    blurhash: 'LSL3V*~U%g-:-oR*Rjt6b_xuniV@',
    cookTime: 40,
    prepTime: 5,
    servings: 4,
    calories: 680,
    ingredients: [
      { id: '1', name: 'Chicken thigh fillets, cubed', quantity: '1.2', unit: 'kg', category: 'meat' },
      { id: '2', name: 'Red curry paste', quantity: '3', unit: 'tbsp', category: 'pantry' },
      { id: '3', name: 'X 400ml tins coconut cream', quantity: '2', unit: 'whole', category: 'dairy' },
      { id: '4', name: 'Coconut milk', quantity: '1', unit: 'tin', category: 'dairy' },
      { id: '5', name: 'Large onions', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Kaffir lime leaves', quantity: '3', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Fish sauce', quantity: '1.5', unit: 'tbsp', category: 'meat' },
      { id: '8', name: 'Brown sugar', quantity: '1.5', unit: 'tsp', category: 'pantry' },
      { id: '9', name: 'Frozen peas', quantity: '1.5', unit: 'cups', category: 'frozen' },
      { id: '10', name: 'Jasmine rice and fresh coriander', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Fry onions 4 min. Add curry paste, fry 1–2 min.',
      'Add chicken, toss, cook 4–5 min.',
      'Add coconut cream/milk, lime leaves, fish sauce, sugar. Simmer 25–30 min.',
      'Add peas last 2–3 min. Serve 1/3. Refrigerate rest in 2 containers.',
    ],
    tags: ['Family Budget', 'Dinner'],
  },
  'FB-D2': {
    name: 'Chicken Biryani (from Sunday curry)',
    description: 'Sunday\'s curry is the biryani base — the hardest part is already done.',
    imageUrl: IMG + 'chicken_biryani.png',
    blurhash: 'LZMjKz?bx]xa?^RkRPj[gOjZWAfP',
    cookTime: 35,
    prepTime: 5,
    servings: 4,
    calories: 620,
    ingredients: [
      { id: '1', name: 'Leftover curry chicken', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Basmati rice, rinsed', quantity: '2', unit: 'cups', category: 'pantry' },
      { id: '3', name: 'Turmeric water', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '4', name: 'Fried onion slices', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Yoghurt stirred into curry', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { id: '6', name: 'Fresh coriander', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Fried shallots', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Par-cook basmati rice 8 min (70% done). Drain.',
      'Warm curry gently in heavy pot. Stir in yoghurt.',
      'Layer half rice over curry. Drizzle turmeric water. Add remaining rice.',
      'Top with fried onions. Seal lid (or foil + lid). Cook on lowest heat 20 min.',
      'Fluff gently from edges. Serve with raita.',
    ],
    tags: ['Family Budget', 'Dinner'],
  },
  'FB-D3': {
    name: 'Honey Soy Salmon with Hokkien Noodles & Greens',
    description: 'Most-searched weeknight recipe in Australia. Honey soy glaze is the key.',
    imageUrl: IMG + 'honey_soy_salmon_with_hokkien_noodles_greens.png',
    blurhash: 'LDJQs6~BpJpIE4skRPWU180gDhv~',
    cookTime: 25,
    prepTime: 5,
    servings: 4,
    calories: 580,
    ingredients: [
      { id: '1', name: 'X salmon fillets', quantity: '4', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Honey', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '3', name: 'Low-sodium soy', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '4', name: 'Sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Garlic clove', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Fresh hokkien noodles', quantity: '200', unit: 'g', category: 'pantry' },
      { id: '7', name: 'Broccolini', quantity: '1', unit: 'bunch', category: 'produce' },
      { id: '8', name: 'Bok choy halves', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '9', name: 'Oyster sauce', quantity: '1', unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Mix glaze. Marinate salmon 10 min if time allows.',
      'Cook hokkien noodles per packet (boiling water, drain 2 min).',
      'Pan-fry salmon 3–4 min per side, basting with glaze.',
      'Stir-fry broccolini and bok choy with oyster sauce 3–4 min.',
      'Toss greens through noodles. Plate. Top with salmon.',
    ],
    tags: ['Family Budget', 'Dinner'],
  },
  'FB-D4': {
    name: 'Spaghetti Bolognese (beef or turkey mince)',
    description: 'Australia\'s most-cooked family dinner. Cook 1kg mince — freeze half sauce.',
    imageUrl: IMG + 'spaghetti_bolognese_beef_or_turkey_mince.png',
    blurhash: 'L7IqiW~Du4yDQ+4:DiVs.T55QmeS',
    cookTime: 40,
    prepTime: 5,
    servings: 4,
    calories: 680,
    ingredients: [
      { id: '1', name: 'Lean beef mince OR turkey mince', quantity: '1', unit: 'kg', category: 'meat' },
      { id: '2', name: 'Spaghetti', quantity: '400', unit: 'g', category: 'pantry' },
      { id: '3', name: 'Tins crushed tomatoes', quantity: '400', unit: 'g', category: 'produce' },
      { id: '4', name: 'Onion', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Garlic cloves', quantity: '3', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Tomato paste', quantity: '1', unit: 'tbsp', category: 'produce' },
      { id: '7', name: 'Oregano', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Basil + 1 tbsp Worcestershire sauce', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '9', name: 'Parmesan', quantity: '1', unit: 'whole', category: 'dairy' },
    ],
    instructions: [
      'Fry onion 3 min, garlic 1 min. Brown all 1kg mince 8–10 min.',
      'Scoop half mince into container — refrigerate (becomes Thu nachos).',
      'Add tomato paste, tomatoes, Worcestershire, herbs to remaining mince. Simmer 20–25 min.',
      'Boil pasta per packet. Toss with sauce. Serve with parmesan.',
    ],
    tags: ['Family Budget', 'Dinner'],
  },
  'FB-D5': {
    name: 'Garlic Butter Prawn Pasta',
    description: '25-minute Friday dinner that tastes like a Sydney waterfront restaurant.',
    imageUrl: IMG + 'garlic_butter_prawn_pasta.png',
    blurhash: 'L9IEX?9GGd~V-.?HMxRk0pMwq@D*',
    cookTime: 25,
    prepTime: 5,
    servings: 4,
    calories: 620,
    ingredients: [
      { id: '1', name: 'Raw prawn meat', quantity: '400', unit: 'g', category: 'meat' },
      { id: '2', name: 'Linguine or spaghetti', quantity: '400', unit: 'g', category: 'pantry' },
      { id: '3', name: 'Garlic cloves, sliced', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Butter', quantity: '60', unit: 'g', category: 'dairy' },
      { id: '5', name: 'Olive oil', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: 'Dry white wine or chicken stock', quantity: '0.5', unit: 'cup', category: 'meat' },
      { id: '7', name: 'Juice', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '8', name: 'Zest 1 lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '9', name: 'Flat-leaf parsley', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '10', name: 'Chilli flakes', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Parmesan', quantity: '1', unit: 'whole', category: 'dairy' },
    ],
    instructions: [
      'Cook pasta. Reserve 1/2 cup pasta water before draining.',
      'Heat butter + oil. Add garlic + chilli 1 min.',
      'Add prawns, cook 90 sec per side. Remove.',
      'Deglaze with wine 2 min. Add pasta + pasta water. Return prawns.',
      'Add lemon + parsley. Toss. Serve with parmesan.',
    ],
    tags: ['Family Budget', 'Dinner'],
  },
  'FB-D6': {
    name: 'Lamb/Turkey Kofta Wraps (Saturday Lunch/Dinner)',
    description: 'Middle Eastern. Same kofta mixture works as both Saturday lunch and dinner base.',
    imageUrl: IMG + 'lamb_turkey_kofta_wraps.png',
    blurhash: 'LTKKcw^+b^WY%NR*Rjj[*0WEaKt6',
    cookTime: 30,
    prepTime: 5,
    servings: 4,
    calories: 610,
    ingredients: [
      { id: '1', name: 'Lamb mince OR turkey mince', quantity: '500', unit: 'g', category: 'meat' },
      { id: '2', name: 'Cumin', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '3', name: 'Coriander', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '4', name: 'Cinnamon', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Garlic powder', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '6', name: 'Onion grated', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Parsley', quantity: '2', unit: 'tbsp', category: 'produce' },
      { id: '8', name: 'Large wraps or flatbreads', quantity: '4', unit: 'whole', category: 'bakery' },
      { id: '9', name: 'Tzatziki: 1 cup yoghurt', quantity: '1', unit: 'whole', category: 'dairy' },
      { id: '10', name: 'Cucumber grated', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Garlic', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Mix mince with spices, onion and parsley. Shape into koftas.',
      'BBQ or pan-fry 3–4 min per side.',
      'Make tzatziki. Assemble wraps with lettuce, tabbouleh and tzatziki.',
    ],
    tags: ['Family Budget', 'Dinner'],
  },
  'FB-D7': {
    name: 'Slow-Cooked Pulled Lamb Shoulder (Sat 2pm start)',
    description: 'Start Saturday 2pm. Ready Sunday morning for two stunning Sunday meals.',
    imageUrl: IMG + 'slow_cooked_pulled_lamb_shoulder.png',
    blurhash: 'LiHdvmV@Rkt7~UM|M|ayxtRkRjWB',
    cookTime: 15,
    prepTime: 5,
    servings: 4,
    calories: 580,
    ingredients: [
      { id: '1', name: '2kg lamb shoulder, bone-in', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Large onion', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Garlic cloves', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Crushed tomatoes', quantity: '1', unit: 'tin', category: 'produce' },
      { id: '5', name: 'Stock + 1 tbsp cumin', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '6', name: 'Stock + 1 tbsp coriander', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '7', name: 'Stock + 1 tbsp paprika', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '8', name: 'Cinnamon', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '9', name: 'Tomato paste', quantity: '2', unit: 'tbsp', category: 'produce' },
      { id: '10', name: 'Honey', quantity: '1', unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Rub lamb with spice mix.',
      'Place onion and garlic in slow cooker. Mix tomatoes, stock, paste, honey. Pour over.',
      'Lay lamb on top. Cook LOW 8–10 hrs (Sat 2pm → Sun morning).',
      'Sunday: shred with two forks. Skim fat from juices.',
    ],
    tags: ['Family Budget', 'Dinner'],
  },
  'FB-D8': {
    name: 'Middle Eastern Pulled Lamb Feast (Sunday dinner)',
    description: 'The Sunday showpiece — the slow cooker did all the work.',
    imageUrl: IMG + 'middle_eastern_pulled_lamb_feast.png',
    blurhash: 'L6HUweV?.Tt800Ip9GaxTf9G8wRO',
    cookTime: 20,
    prepTime: 5,
    servings: 4,
    calories: 640,
    ingredients: [
      { id: '1', name: 'Remaining pulled lamb', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Couscous cooked in boiling stock', quantity: '1.5', unit: 'cups', category: 'pantry' },
      { id: '3', name: 'Greek yoghurt', quantity: '1', unit: 'cup', category: 'dairy' },
      { id: '4', name: 'Pinch cumin', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '5', name: 'Pomegranate seeds or dried cranberries', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Fresh mint', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '7', name: 'Lebanese cucumber diced', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Lemon wedges', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '9', name: 'Flatbreads', quantity: '1', unit: 'whole', category: 'bakery' },
    ],
    instructions: [
      'Warm pulled lamb in pot with splash of water 5–8 min.',
      'Cook couscous: boiling stock over couscous, cover 5 min, fluff.',
      'Plate couscous as base, pile lamb on top.',
      'Dot with yoghurt, scatter pomegranate, mint and cucumber.',
      'Serve with warm flatbreads and lemon wedges.',
      'Smart Family Budget Plan — Week 1 — Foundation (All New)',
      'Week 1 — Foundation (All New)',
      'All new recipes this week',
      'Breakfast',
      'Lunch',
      'Dinner',
      'Day 1',
      'Saturday',
      'FB-B1',
      'Bircher Muesli with Poached Pears',
      '~470 kcal',
      'FB-L4',
      'Lamb (or Turkey) Kofta Wraps with Tzatziki',
      '~610 kcal',
      'FB-D6',
      'Lamb/Turkey Kofta Wraps (Saturday Lunch/Dinner)',
      '~610 kcal',
      'Day 2',
      'Sunday',
      'FB-B7',
      'Shakshuka for Four',
      '~440 kcal',
      'FB-L5',
      'Pulled Lamb Flatbread Pizzas',
      '~550 kcal',
      'FB-D8',
      'Middle Eastern Pulled Lamb Feast (Sunday dinner)',
      '~640 kcal',
      'Day 3',
      'Monday',
      'FB-B3',
      'Banana Overnight Oats with Honey & Almonds',
      '~480 kcal',
      'FB-L1',
      'Chicken Caesar Wrap',
      '~580 kcal',
      'FB-D2',
      'Chicken Biryani (from Sunday curry)',
      '~620 kcal',
      'Day 4',
      'Tuesday',
      'FB-B4',
      'Vegemite & Avocado Toast with Eggs',
      '~490 kcal',
      'FB-L2',
      'Tinned Salmon & Avocado Rice Paper Rolls',
      '~390 kcal',
      'FB-D3',
      'Honey Soy Salmon with Hokkien Noodles & Greens',
      '~580 kcal',
      'Day 5',
      'Wednesday',
      'FB-B2',
      'Big Brekkie Board (Bacon, Eggs, Mushrooms, Toast)',
      '~540 kcal',
      'FB-L7',
      'Quinoa Tabbouleh with Chickpeas & Feta',
      '~480 kcal',
      'FB-D4',
      'Spaghetti Bolognese (beef or turkey mince)',
      '~680 kcal',
      'Day 6',
      'Thursday',
      'FB-B6',
      'Smoothie Bowls with Granola & Seasonal Fruit',
      '~480 kcal',
      'FB-L6',
      'Nachos with Beef/Turkey Mince & Jalapeño',
      '~640 kcal',
      'FB-D4',
      'Spaghetti Bolognese (beef or turkey mince)',
      '~680 kcal',
      'Day 7',
      'Friday',
      'FB-B5',
      'Greek Yoghurt with Mixed Berries & Chia Seeds',
      '~380 kcal',
      'FB-L3',
      'Chicken Fried Rice',
      '~520 kcal',
      'FB-D5',
      'Garlic Butter Prawn Pasta',
      '~620 kcal',
      'Avg. daily',
      '~430–540 kcal · ~16–28g protein',
      '~390–640 kcal · ~18–42g protein',
      '~580–680 kcal · ~38–52g protein',
      'Daily total: ~2,100–2,600 kcal  |  ~80–100g protein  |  4 serves per recipe',
      'Smart Family Budget Plan — Week 2 — 2 Repeats from W1',
      'Week 2 — 2 Repeats from W1',
      '♻  FB-D1 (curry) and FB-D5 (prawn pasta) repeat',
      'Breakfast',
      'Lunch',
      'Dinner',
      'Day 1',
      'Saturday',
      'FB-B2',
      'Big Brekkie Board (Bacon, Eggs, Mushrooms, Toast)',
      '~540 kcal',
      'FB-L4',
      'Lamb (or Turkey) Kofta Wraps with Tzatziki',
      '~610 kcal',
      'FB-D6',
      'Lamb/Turkey Kofta Wraps (Saturday Lunch/Dinner)',
      '~610 kcal',
      'Day 2',
      'Sunday',
      'W1 return',
      'FB-B1',
      'Bircher Muesli with Poached Pears',
      '~470 kcal',
      'FB-L5',
      'Pulled Lamb Flatbread Pizzas',
      '~550 kcal',
      'FB-D8',
      'Middle Eastern Pulled Lamb Feast (Sunday dinner)',
      '~640 kcal',
      'Day 3',
      'Monday',
      'REPEAT from W1',
      'FB-B3',
      'Banana Overnight Oats with Honey & Almonds',
      '~480 kcal',
      'FB-L1',
      'Chicken Caesar Wrap',
      '~580 kcal',
      'FB-D1',
      'Thai-Style Chicken Thigh Curry (Double Batch)',
      '~680 kcal',
      'Day 4',
      'Tuesday',
      'FB-B4',
      'Vegemite & Avocado Toast with Eggs',
      '~490 kcal',
      'FB-L2',
      'Tinned Salmon & Avocado Rice Paper Rolls',
      '~390 kcal',
      'FB-D2',
      'Chicken Biryani (from Sunday curry)',
      '~620 kcal',
      'Day 5',
      'Wednesday',
      'FB-B7',
      'Shakshuka for Four',
      '~440 kcal',
      'FB-L7',
      'Quinoa Tabbouleh with Chickpeas & Feta',
      '~480 kcal',
      'FB-D3',
      'Honey Soy Salmon with Hokkien Noodles & Greens',
      '~580 kcal',
      'Day 6',
      'Thursday',
      'FB-B6',
      'Smoothie Bowls with Granola & Seasonal Fruit',
      '~480 kcal',
      'FB-L6',
      'Nachos with Beef/Turkey Mince & Jalapeño',
      '~640 kcal',
      'FB-D4',
      'Spaghetti Bolognese (beef or turkey mince)',
      '~680 kcal',
      'Day 7',
      'Friday',
      'REPEAT from W1',
      'FB-B5',
      'Greek Yoghurt with Mixed Berries & Chia Seeds',
      '~380 kcal',
      'FB-L3',
      'Chicken Fried Rice',
      '~520 kcal',
      'FB-D5',
      'Garlic Butter Prawn Pasta',
      '~620 kcal',
      'Avg. daily',
      '~430–540 kcal · ~16–28g protein',
      '~390–640 kcal · ~18–42g protein',
      '~580–680 kcal · ~38–52g protein',
      'Daily total: ~2,100–2,600 kcal  |  ~80–100g protein  |  4 serves per recipe',
      'Smart Family Budget Plan — Week 3 — W1 Returns',
      'Week 3 — W1 Returns',
      '♻  W1 dinner rotation returns in full',
      'Breakfast',
      'Lunch',
      'Dinner',
      'Day 1',
      'Saturday',
      'W1 return',
      'FB-B2',
      'Big Brekkie Board (Bacon, Eggs, Mushrooms, Toast)',
      '~540 kcal',
      'FB-L4',
      'Lamb (or Turkey) Kofta Wraps with Tzatziki',
      '~610 kcal',
      'FB-D6',
      'Lamb/Turkey Kofta Wraps (Saturday Lunch/Dinner)',
      '~610 kcal',
      'Day 2',
      'Sunday',
      'W1 return',
      'FB-B7',
      'Shakshuka for Four',
      '~440 kcal',
      'FB-L5',
      'Pulled Lamb Flatbread Pizzas',
      '~550 kcal',
      'FB-D8',
      'Middle Eastern Pulled Lamb Feast (Sunday dinner)',
      '~640 kcal',
      'Day 3',
      'Monday',
      'W1 return',
      'FB-B3',
      'Banana Overnight Oats with Honey & Almonds',
      '~480 kcal',
      'FB-L1',
      'Chicken Caesar Wrap',
      '~580 kcal',
      'FB-D2',
      'Chicken Biryani (from Sunday curry)',
      '~620 kcal',
      'Day 4',
      'Tuesday',
      'W1 return',
      'FB-B4',
      'Vegemite & Avocado Toast with Eggs',
      '~490 kcal',
      'FB-L3',
      'Chicken Fried Rice',
      '~520 kcal',
      'FB-D3',
      'Honey Soy Salmon with Hokkien Noodles & Greens',
      '~580 kcal',
      'Day 5',
      'Wednesday',
      'W1 return',
      'FB-B6',
      'Smoothie Bowls with Granola & Seasonal Fruit',
      '~480 kcal',
      'FB-L7',
      'Quinoa Tabbouleh with Chickpeas & Feta',
      '~480 kcal',
      'FB-D4',
      'Spaghetti Bolognese (beef or turkey mince)',
      '~680 kcal',
      'Day 6',
      'Thursday',
      'W1 return',
      'FB-B1',
      'Bircher Muesli with Poached Pears',
      '~470 kcal',
      'FB-L6',
      'Nachos with Beef/Turkey Mince & Jalapeño',
      '~640 kcal',
      'FB-D4',
      'Spaghetti Bolognese (beef or turkey mince)',
      '~680 kcal',
      'Day 7',
      'Friday',
      'W1 return',
      'FB-B5',
      'Greek Yoghurt with Mixed Berries & Chia Seeds',
      '~380 kcal',
      'FB-L2',
      'Tinned Salmon & Avocado Rice Paper Rolls',
      '~390 kcal',
      'FB-D5',
      'Garlic Butter Prawn Pasta',
      '~620 kcal',
      'Avg. daily',
      '~430–540 kcal · ~16–28g protein',
      '~390–640 kcal · ~18–42g protein',
      '~580–680 kcal · ~38–52g protein',
      'Daily total: ~2,100–2,600 kcal  |  ~80–100g protein  |  4 serves per recipe',
      'Smart Family Budget Plan — Week 4 — W2 Returns',
      'Week 4 — W2 Returns',
      '♻  W2 dinners return; fresh breakfast variation',
      'Breakfast',
      'Lunch',
      'Dinner',
      'Day 1',
      'Saturday',
      'W2 return',
      'FB-B1',
      'Bircher Muesli with Poached Pears',
      '~470 kcal',
      'FB-L4',
      'Lamb (or Turkey) Kofta Wraps with Tzatziki',
      '~610 kcal',
      'FB-D6',
      'Lamb/Turkey Kofta Wraps (Saturday Lunch/Dinner)',
      '~610 kcal',
      'Day 2',
      'Sunday',
      'W2 return',
      'FB-B7',
      'Shakshuka for Four',
      '~440 kcal',
      'FB-L5',
      'Pulled Lamb Flatbread Pizzas',
      '~550 kcal',
      'FB-D8',
      'Middle Eastern Pulled Lamb Feast (Sunday dinner)',
      '~640 kcal',
      'Day 3',
      'Monday',
      'W2 return',
      'FB-B3',
      'Banana Overnight Oats with Honey & Almonds',
      '~480 kcal',
      'FB-L1',
      'Chicken Caesar Wrap',
      '~580 kcal',
      'FB-D1',
      'Thai-Style Chicken Thigh Curry (Double Batch)',
      '~680 kcal',
      'Day 4',
      'Tuesday',
      'W2 return',
      'FB-B2',
      'Big Brekkie Board (Bacon, Eggs, Mushrooms, Toast)',
      '~540 kcal',
      'FB-L2',
      'Tinned Salmon & Avocado Rice Paper Rolls',
      '~390 kcal',
      'FB-D2',
      'Chicken Biryani (from Sunday curry)',
      '~620 kcal',
      'Day 5',
      'Wednesday',
      'W2 return',
      'FB-B4',
      'Vegemite & Avocado Toast with Eggs',
      '~490 kcal',
      'FB-L7',
      'Quinoa Tabbouleh with Chickpeas & Feta',
      '~480 kcal',
      'FB-D3',
      'Honey Soy Salmon with Hokkien Noodles & Greens',
      '~580 kcal',
      'Day 6',
      'Thursday',
      'W2 return',
      'FB-B6',
      'Smoothie Bowls with Granola & Seasonal Fruit',
      '~480 kcal',
      'FB-L6',
      'Nachos with Beef/Turkey Mince & Jalapeño',
      '~640 kcal',
      'FB-D4',
      'Spaghetti Bolognese (beef or turkey mince)',
      '~680 kcal',
      'Day 7',
      'Friday',
      'W2 return',
      'FB-B5',
      'Greek Yoghurt with Mixed Berries & Chia Seeds',
      '~380 kcal',
      'FB-L3',
      'Chicken Fried Rice',
      '~520 kcal',
      'FB-D5',
      'Garlic Butter Prawn Pasta',
      '~620 kcal',
      'Avg. daily',
      '~430–540 kcal · ~16–28g protein',
      '~390–640 kcal · ~18–42g protein',
      '~580–680 kcal · ~38–52g protein',
      'Daily total: ~2,100–2,600 kcal  |  ~80–100g protein  |  4 serves per recipe',
      'Solo Active Professional — Plan 1 (Daily Fresh)',
      '4-Week Plan',
      'Active lifestyle · ~2,000–2,400 kcal · Dinner → next day\'s lunch · 1 serve',
      'W1 All New',
      'W2 1–2 Repeats',
      'W3 W1 Returns',
      'W4 W2 Returns',
      'Recipe Bank — Solo Active Professional — Plan 1 (Daily Fresh)',
      'All recipes for this plan listed below. Use the recipe codes (e.g. LE-B1, VG-D3) to cross-reference the weekly schedule tables. Full ingredients and method for each recipe.',
      'Breakfasts',
    ],
    tags: ['Family Budget', 'Dinner'],
  },
};

const GRAB_GO_BREAKFAST: CuratedRecipe = {
  name: 'Grab & go',
  description: 'No cooking — grab a quick option on your way out.',
  imageUrl: IMG + 'bircher_muesli_with_poached_pears.png',
  blurhash: 'LEKdYn4:cZ%L~p-oMxWB0LD%n2WE',
  cookTime: 0, prepTime: 0, servings: 4, calories: 0,
  ingredients: [], instructions: [], tags: ['Grab & Go', 'No Cook'],
};
const BUY_OUT_LUNCH: CuratedRecipe = {
  name: 'Buy out',
  description: 'No cooking — pick up a lunch out.',
  imageUrl: IMG + 'bircher_muesli_with_poached_pears.png',
  blurhash: 'LEKdYn4:cZ%L~p-oMxWB0LD%n2WE',
  cookTime: 0, prepTime: 0, servings: 4, calories: 0,
  ingredients: [], instructions: [], tags: ['Buy Out', 'No Cook'],
};
const BUY_OUT_DINNER: CuratedRecipe = {
  ...BUY_OUT_LUNCH,
  description: 'No cooking tonight — buy dinner out or order in. No groceries needed.',
};

const FAMILY_BUDGET_BANK: PlanBank = {
  recipes: RECIPES,
  breakfastWeekendCook: ['FB-B2', 'FB-B4', 'FB-B6', 'FB-B7'],
  breakfastWeekdayEasy: ['FB-B1', 'FB-B3', 'FB-B5'],
  lunchCook: ['FB-L1', 'FB-L2', 'FB-L3', 'FB-L4', 'FB-L5', 'FB-L6', 'FB-L7'],
  dinnersFresh: ['FB-D1', 'FB-D2', 'FB-D3', 'FB-D4', 'FB-D5', 'FB-D6', 'FB-D7'],
  batchMains: ['FB-D1', 'FB-D2', 'FB-D3', 'FB-D4', 'FB-D5', 'FB-D6', 'FB-D7', 'FB-D8', 'FB-L1', 'FB-L2', 'FB-L3', 'FB-L4', 'FB-L5', 'FB-L6', 'FB-L7'],
  grabGoBreakfast: GRAB_GO_BREAKFAST,
  buyOutLunch: BUY_OUT_LUNCH,
  buyOutDinner: BUY_OUT_DINNER,
};

export const FAMILY_BUDGET_MAX_BATCH_RECIPES = FAMILY_BUDGET_BANK.batchMains.length;

export function buildFamilyBudgetMeals(
  durationDays: number,
  prefs: CookingPreferences = DEFAULT_COOKING_PREFS,
  startWeekday: number = 0,
): ScheduledMeal[] {
  return buildPlanMeals(FAMILY_BUDGET_BANK, durationDays, prefs, startWeekday);
}
