// ─────────────────────────────────────────────────────────────────────────
// Light & Easy — recipe bank + scheduling
//
// Recipes transcribed from the "4-Week Meal Plan Collection" (LE- codes).
// Schedulable: feeds the shared plan engine (plan-engine.ts) exactly like
// High-Protein Simple, so the day-by-day browser and apply flow honour the
// user's Duration + cooking-style (batch / daily, leftovers, serving size).
// ─────────────────────────────────────────────────────────────────────────
import {
  buildPlanMeals,
  type CuratedRecipe,
  type PlanBank,
} from './plan-engine';
import {
  type CookingPreferences,
  type ScheduledMeal,
  DEFAULT_COOKING_PREFS,
} from './high-protein-plan';

const IMG =
  'https://wcjsrhdlnmfugdjtvadj.supabase.co/storage/v1/object/public/Light%20%26%20Easy%20Meal%20Plan/';

const RECIPES: Record<string, CuratedRecipe> = {
  'LE-B1': {
    name: 'Bircher Muesli with Grated Apple & Yoghurt',
    description: 'Soak overnight, grab-and-go in the morning. Creamy, filling and naturally sweet.',
    imageUrl: IMG + 'bircher_muesli_with_grated_apple_yoghurt.png',
    blurhash: 'LJKA$n~Wbwoz?bD*RjfQA0t8s+xa',
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    calories: 340,
    ingredients: [
      { id: '1', name: 'Rolled oats', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '2', name: 'Reduced-fat milk or oat milk', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { id: '3', name: 'Small apple, grated', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Low-fat Greek yoghurt', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { id: '5', name: 'Honey', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Chia or flax seeds', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '7', name: 'Pinch cinnamon', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Night before: stir oats and milk in a jar. Refrigerate overnight.',
      'Morning: stir in grated apple, yoghurt, honey, seeds and cinnamon.',
      'Eat straight from the jar.',
    ],
    tags: ['Light & Easy', 'Breakfast', 'Quick'],
  },
  'LE-B2': {
    name: 'Soft Scrambled Eggs on Wholegrain Toast',
    description: 'A classic done right. Low and slow keeps eggs creamy and easy to digest.',
    imageUrl: IMG + 'soft_scrambled_eggs_on_wholegrain_toast.png',
    blurhash: 'LUKd9w^*tls;~VNGRjjZNfogngt6',
    cookTime: 8,
    prepTime: 5,
    servings: 1,
    calories: 320,
    ingredients: [
      { id: '1', name: 'Free-range eggs', quantity: '2', unit: 'whole', category: 'dairy' },
      { id: '2', name: 'Reduced-fat milk', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { id: '3', name: 'Wholegrain bread', quantity: '1', unit: 'slice', category: 'bakery' },
      { id: '4', name: 'Small tomato, sliced', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Black pepper', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Whisk eggs with milk and pepper.',
      'Heat oil in non-stick pan on low-medium. Pour in eggs.',
      'Stir gently every 30 sec. Remove when still slightly glossy.',
      'Toast bread. Serve eggs on toast with sliced tomato.',
    ],
    tags: ['Light & Easy', 'Breakfast', 'Quick'],
  },
  'LE-B3': {
    name: 'Banana & Nut Butter Smoothie',
    description: 'Blended in 3 minutes. Perfect when appetite is low in the morning.',
    imageUrl: IMG + 'banana_nut_butter_smoothie.png',
    blurhash: 'LLLD#+~qJD%1xtt7M|WB0LxtaJt7',
    cookTime: 3,
    prepTime: 5,
    servings: 1,
    calories: 310,
    ingredients: [
      { id: '1', name: 'Ripe banana', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '2', name: 'Reduced-fat milk or oat milk', quantity: '1', unit: 'cup', category: 'dairy' },
      { id: '3', name: 'Low-fat Greek yoghurt', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { id: '4', name: 'Almond or peanut butter', quantity: '1', unit: 'tsp', category: 'dairy' },
      { id: '5', name: 'Oats', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: 'Pinch cinnamon', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Place all ingredients in a blender.',
      'Blend until smooth, 30–45 seconds.',
      'Drink immediately or refrigerate up to 4 hours.',
    ],
    tags: ['Light & Easy', 'Breakfast', 'Quick'],
  },
  'LE-B4': {
    name: 'Warm Stewed Apple with Oats & Almonds',
    description: 'A cooked brekkie, naturally sweet with no added sugar needed.',
    imageUrl: IMG + 'warm_stewed_apple_with_oats_almonds.png',
    blurhash: 'LEHny$~WX.tS4:IoMxe.14NeMcs8',
    cookTime: 10,
    prepTime: 5,
    servings: 1,
    calories: 330,
    ingredients: [
      { id: '1', name: 'Apple, peeled and diced', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '2', name: 'Rolled oats', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '3', name: 'Water or low-fat milk', quantity: '1', unit: 'cup', category: 'dairy' },
      { id: '4', name: 'Raw almonds, chopped', quantity: '6', unit: 'whole', category: 'pantry' },
      { id: '5', name: 'Cinnamon', quantity: '0.25', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Honey', quantity: '1', unit: 'tsp', category: 'pantry' },
    ],
    instructions: [
      'Cook apple in small saucepan with 2 tbsp water, 5–6 min until soft.',
      'Cook oats in separate pot with water or milk, 3–5 min.',
      'Top oats with stewed apple, almonds, cinnamon and honey.',
    ],
    tags: ['Light & Easy', 'Breakfast', 'Quick'],
  },
  'LE-B5': {
    name: 'Greek Yoghurt with Mixed Berries & Chia Seeds',
    description: 'No cooking at all. A complete breakfast in 2 minutes.',
    imageUrl: IMG + 'greek_yoghurt_with_mixed_berries_chia_seeds.png',
    blurhash: 'LWK^vl?bx[jF~pM{R*ofx[RjV@tR',
    cookTime: 2,
    prepTime: 5,
    servings: 1,
    calories: 300,
    ingredients: [
      { id: '1', name: 'Plain low-fat Greek yoghurt', quantity: '0.75', unit: 'cup', category: 'dairy' },
      { id: '2', name: 'Mixed berries', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '3', name: 'Chia seeds', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '4', name: 'Honey', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Small handful muesli or oats', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Thaw frozen berries overnight if needed.',
      'Spoon yoghurt into bowl. Top with berries, chia, honey and muesli.',
    ],
    tags: ['Light & Easy', 'Breakfast', 'Quick'],
  },
  'LE-B6': {
    name: 'Veggie Omelette on Rye with Spinach',
    description: 'Weekend brekkie. Rye bread is lower GI — a wonderful earthy flavour.',
    imageUrl: IMG + 'veggie_omelette_on_rye_with_spinach.png',
    blurhash: 'LFJ7~[^%pJx]xBIAIUoepfM~R4t6',
    cookTime: 12,
    prepTime: 5,
    servings: 1,
    calories: 350,
    ingredients: [
      { id: '1', name: 'Free-range eggs', quantity: '2', unit: 'whole', category: 'dairy' },
      { id: '2', name: 'Milk', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { id: '3', name: 'Handful baby spinach', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Button mushrooms, sliced', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Cherry tomatoes, halved', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '7', name: 'Rye bread', quantity: '1', unit: 'slice', category: 'bakery' },
      { id: '8', name: 'Black pepper', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Whisk eggs, milk and pepper.',
      'Fry mushrooms in oil 2 min. Add spinach and tomatoes 1 min.',
      'Pour egg mixture over. Cook 2–3 min. Fold in half.',
      'Toast rye bread. Serve omelette alongside.',
    ],
    tags: ['Light & Easy', 'Breakfast'],
  },
  'LE-B7': {
    name: 'Ricotta Toast with Fresh Fig & Walnuts',
    description: 'Elegant and indulgent-feeling but light. Figs April–June in Australia.',
    imageUrl: IMG + 'ricotta_toast_with_fresh_fig_walnuts.png',
    blurhash: 'LIKKD:01OG%L~9o#M|n$.8NGVsof',
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    calories: 330,
    ingredients: [
      { id: '1', name: 'Rye or sourdough bread', quantity: '1', unit: 'slice', category: 'bakery' },
      { id: '2', name: 'Smooth ricotta', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { id: '3', name: 'Fresh fig', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '4', name: 'Walnuts, broken', quantity: '4', unit: 'whole', category: 'pantry' },
      { id: '5', name: 'Honey', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Pinch cinnamon', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Toast bread lightly.',
      'Spread ricotta generously.',
      'Arrange fig on top. Scatter walnuts. Drizzle honey and cinnamon.',
      'Lunches',
    ],
    tags: ['Light & Easy', 'Breakfast', 'Quick'],
  },
  'LE-L1': {
    name: 'Tinned Salmon & Avocado Rice Paper Rolls',
    description: 'Fresh, light and no cooking required. Vietnamese-style.',
    imageUrl: IMG + 'tinned_salmon_avocado_rice_paper_rolls.png',
    blurhash: 'LUIr7{?b.9oz~pj]WYt7.8RkRPWB',
    cookTime: 15,
    prepTime: 5,
    servings: 1,
    calories: 390,
    ingredients: [
      { id: '1', name: 'Tin salmon in springwater, drained', quantity: '95', unit: 'g', category: 'meat' },
      { id: '2', name: 'Ripe avocado, sliced', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Cucumber, julienned', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Handful baby spinach', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Rice paper rounds', quantity: '4', unit: 'whole', category: 'pantry' },
      { id: '6', name: 'Tamari or sweet chilli for dipping', quantity: '1', unit: 'tbsp', category: 'produce' },
    ],
    instructions: [
      'Soak rice paper 15 sec in warm water until just soft.',
      'Lay flat. Layer spinach, cucumber, avocado and salmon on lower third.',
      'Fold sides in, roll up firmly. Serve with dipping sauce.',
    ],
    tags: ['Light & Easy', 'Lunch'],
  },
  'LE-L2': {
    name: 'Chickpea, Spinach & Roasted Capsicum Salad',
    description: 'Filling, anti-inflammatory and colourful. No cooking required.',
    imageUrl: IMG + 'chickpea_spinach_roasted_capsicum_salad.png',
    blurhash: 'LEJ@ah_3Xn%2~99GM{n%.SIAR5WV',
    cookTime: 10,
    prepTime: 5,
    servings: 1,
    calories: 380,
    ingredients: [
      { id: '1', name: 'Tin chickpeas, rinsed', quantity: '400', unit: 'g', category: 'produce' },
      { id: '2', name: 'Baby spinach', quantity: '2', unit: 'handfuls', category: 'produce' },
      { id: '3', name: 'Strips roasted capsicum', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Cherry tomatoes', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '5', name: 'Tahini', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: 'Lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Olive oil', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '8', name: 'Cumin', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Whisk dressing ingredients. Add water to loosen.',
      'Combine all salad ingredients. Drizzle dressing and toss.',
    ],
    tags: ['Light & Easy', 'Lunch', 'Quick'],
  },
  'LE-L3': {
    name: 'Miso Silken Tofu Soup with Rice Noodles & Bok Choy',
    description: 'Simple Japanese-inspired broth. Warming and low-sodium.',
    imageUrl: IMG + 'miso_silken_tofu_soup_with_rice_noodles_bok_choy.png',
    blurhash: 'LaLD}a?b%Nxu~WRjM{ofWGxuadWB',
    cookTime: 15,
    prepTime: 5,
    servings: 1,
    calories: 360,
    ingredients: [
      { id: '1', name: 'White miso paste', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '2', name: 'Silken tofu, cubed', quantity: '150', unit: 'g', category: 'pantry' },
      { id: '3', name: 'Nest thin rice noodles', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '4', name: 'Bok choy heads, halved', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Boiling water', quantity: '2', unit: 'cups', category: 'pantry' },
      { id: '6', name: 'Spring onion, sliced', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Soak noodles in boiling water 5 min. Drain.',
      'Simmer 2 cups water. Dissolve miso in 2 tbsp warm water, stir in.',
      'Add bok choy 2 min. Gently add tofu 1–2 min.',
      'Add noodles to bowl, ladle soup over. Top with spring onion.',
    ],
    tags: ['Light & Easy', 'Lunch'],
  },
  'LE-L4': {
    name: 'Red Lentil & Vegetable Soup with Wholegrain Crackers',
    description: 'Batch-friendly. Make a big pot and refrigerate up to 3 days.',
    imageUrl: IMG + 'red_lentil_vegetable_soup_with_crackers.png',
    blurhash: 'L8J*I,00.T-n00?bD%D*B?t7H=.8',
    cookTime: 25,
    prepTime: 5,
    servings: 1,
    calories: 390,
    ingredients: [
      { id: '1', name: 'Red lentils, rinsed', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '2', name: 'Carrot', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Celery', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Zucchini, diced', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Garlic clove, minced', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '6', name: 'Low-sodium veg stock', quantity: '2', unit: 'cups', category: 'pantry' },
      { id: '7', name: 'Cumin', quantity: '0.5', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Turmeric', quantity: '0.5', unit: 'tsp', category: 'pantry' },
      { id: '9', name: 'Wholegrain crackers', quantity: '4', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Fry garlic and spices 30 sec. Add carrot and celery 2–3 min.',
      'Add lentils, zucchini and stock. Simmer 18–20 min.',
      'Blend partially. Serve with crackers.',
    ],
    tags: ['Light & Easy', 'Lunch'],
  },
  'LE-L5': {
    name: 'Tuna & Cannellini Bean Salad',
    description: 'A complete meal straight from the pantry. Satisfying and light.',
    imageUrl: IMG + 'tuna_cannellini_bean_salad.png',
    blurhash: 'LKK-OQ~p.S%M_NRjM{t7Kkx]Vrn$',
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    calories: 380,
    ingredients: [
      { id: '1', name: 'Tin tuna in springwater, drained', quantity: '95', unit: 'g', category: 'meat' },
      { id: '2', name: 'Tin cannellini beans, rinsed', quantity: '400', unit: 'g', category: 'pantry' },
      { id: '3', name: 'Rocket or mixed leaves', quantity: '2', unit: 'handfuls', category: 'produce' },
      { id: '4', name: 'Cherry tomatoes', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '5', name: 'Cucumber, sliced', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '7', name: 'Lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Black pepper', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Combine tuna, beans, rocket, tomatoes and cucumber.',
      'Drizzle olive oil and lemon. Toss and season. Serve.',
    ],
    tags: ['Light & Easy', 'Lunch', 'Quick'],
  },
  'LE-L6': {
    name: 'White Bean & Vegetable Minestrone',
    description: 'Italian classic, Aussie-style. Use seasonal vegetables.',
    imageUrl: IMG + 'white_bean_vegetable_minestrone.png',
    blurhash: 'LPJ@Xa?ax^xu~VIVIUjYK5%Mi_jY',
    cookTime: 25,
    prepTime: 5,
    servings: 1,
    calories: 390,
    ingredients: [
      { id: '1', name: 'Cannellini beans, rinsed', quantity: '0.5', unit: 'tin', category: 'pantry' },
      { id: '2', name: 'Diced tomatoes', quantity: '0.5', unit: 'tin', category: 'produce' },
      { id: '3', name: 'Carrot', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Celery', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Zucchini, diced', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Low-sodium veg stock', quantity: '2', unit: 'cups', category: 'pantry' },
      { id: '7', name: 'Small pasta', quantity: '0.25', unit: 'cup', category: 'pantry' },
      { id: '8', name: 'Garlic clove', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '9', name: 'Fresh basil', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Fry garlic, carrot, celery 3–4 min.',
      'Add tomatoes, stock, zucchini and beans. Bring to boil.',
      'Add pasta. Simmer 10–12 min. Top with basil.',
    ],
    tags: ['Light & Easy', 'Lunch'],
  },
  'LE-L7': {
    name: 'Warm French Lentil & Roasted Beetroot Salad',
    description: 'Hearty Sunday lunch. Pre-cooked beetroot from vacuum packs.',
    imageUrl: IMG + 'warm_french_lentil_roasted_beetroot_salad.png',
    blurhash: 'LPKnJ1?a_N-;?aM{ozt7~qt8IARj',
    cookTime: 10,
    prepTime: 5,
    servings: 1,
    calories: 390,
    ingredients: [
      { id: '1', name: 'French/Puy lentils, rinsed', quantity: '0.5', unit: 'tin', category: 'pantry' },
      { id: '2', name: 'Pre-cooked beetroot pieces, sliced', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Baby spinach', quantity: '2', unit: 'handfuls', category: 'produce' },
      { id: '4', name: 'Balsamic', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '5', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Crumbled goat\'s cheese or feta', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { id: '7', name: 'Handful pumpkin seeds', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Warm lentils briefly if desired.',
      'Arrange spinach as base. Top with lentils, beetroot.',
      'Drizzle dressing. Scatter cheese and seeds.',
      'Dinners',
    ],
    tags: ['Light & Easy', 'Lunch', 'Quick'],
  },
  'LE-D1': {
    name: 'Baked Salmon with Steamed Broccolini & Brown Rice',
    description: 'Classic and nutritious. Omega-3 rich salmon — a weekly heart health staple.',
    imageUrl: IMG + 'baked_salmon_with_steamed_broccolini_brown_rice.png',
    blurhash: 'LLG*m1~BK6OYoeV@WBWW5YEMn3wJ',
    cookTime: 25,
    prepTime: 5,
    servings: 1,
    calories: 450,
    ingredients: [
      { id: '1', name: 'X 120–150g salmon fillet', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '3', name: 'Lemon', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Cooked brown rice', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '5', name: 'Broccolini', quantity: '1', unit: 'bunch', category: 'produce' },
      { id: '6', name: 'Fresh or dried dill, black pepper', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Preheat oven 200C. Line baking tray.',
      'Drizzle salmon with olive oil and lemon. Season. Bake 12–15 min.',
      'Microwave rice 90 sec. Steam broccolini 3–4 min.',
      'Plate rice, top with salmon and broccolini.',
    ],
    tags: ['Light & Easy', 'Dinner'],
  },
  'LE-D2': {
    name: 'Steamed Chicken Breast with Sweet Potato Mash & Peas',
    description: 'Simple comfort food. Sweet potato has lower GI than regular potato.',
    imageUrl: IMG + 'steamed_chicken_breast_with_sweet_potato_mash_peas.png',
    blurhash: 'LWKTxe?Hx^t6~BRkWCn$OZofi^t7',
    cookTime: 30,
    prepTime: 5,
    servings: 1,
    calories: 430,
    ingredients: [
      { id: '1', name: 'Chicken breast', quantity: '120', unit: 'g', category: 'meat' },
      { id: '2', name: 'Medium sweet potato', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Frozen peas', quantity: '0.5', unit: 'cup', category: 'frozen' },
      { id: '4', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Low-fat milk', quantity: '0.25', unit: 'cup', category: 'dairy' },
      { id: '6', name: 'Fresh or dried parsley, black pepper', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Boil sweet potato cubes 12–15 min until tender.',
      'Steam or simmer chicken breast 15 min until cooked.',
      'Microwave peas 1–2 min. Mash sweet potato with milk and oil.',
      'Slice chicken. Serve over mash with peas and parsley.',
    ],
    tags: ['Light & Easy', 'Dinner'],
  },
  'LE-D3': {
    name: 'Barramundi in a Bag with Roasted Vegetables',
    description: 'Barramundi is Australia\'s native sustainable fish — mild and foolproof in foil.',
    imageUrl: IMG + 'barramundi_in_a_bag_with_roasted_vegetables.png',
    blurhash: 'L9Km^F~WO]-;=_00Dioz0L4.McRP',
    cookTime: 25,
    prepTime: 5,
    servings: 1,
    calories: 430,
    ingredients: [
      { id: '1', name: 'Barramundi fillet', quantity: '150', unit: 'g', category: 'meat' },
      { id: '2', name: 'Zucchini', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Cherry tomatoes', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '4', name: 'Capsicum', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Zest', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '7', name: 'Juice 1/2 lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Fresh or dried thyme, black pepper', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Preheat oven 200C. Place veg on large foil sheet.',
      'Drizzle with oil. Lay barramundi on top with lemon, thyme, pepper.',
      'Fold foil into sealed parcel. Bake 18–20 min. Open at table.',
    ],
    tags: ['Light & Easy', 'Dinner'],
  },
  'LE-D4': {
    name: 'Turkey Mince Stir-Fry with Quinoa',
    description: 'Turkey mince is lean, mild and available at Woolworths. Quick and protein-packed.',
    imageUrl: IMG + 'turkey_mince_stir_fry_with_quinoa.png',
    blurhash: 'LaJ*I]-p%ht8?bWBbHay%%bbMyof',
    cookTime: 25,
    prepTime: 5,
    servings: 1,
    calories: 450,
    ingredients: [
      { id: '1', name: 'Lean turkey mince', quantity: '100', unit: 'g', category: 'meat' },
      { id: '2', name: 'Quinoa, rinsed', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '3', name: 'Broccolini florets', quantity: '1', unit: 'cup', category: 'produce' },
      { id: '4', name: 'Snow peas', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '5', name: 'Red capsicum', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Low-sodium tamari', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '7', name: 'Sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Ginger', quantity: '0.5', unit: 'tsp', category: 'produce' },
    ],
    instructions: [
      'Cook quinoa in 1 cup water 12–15 min. Set aside.',
      'Stir-fry turkey in sesame oil 4–5 min. Add broccolini and capsicum 2–3 min.',
      'Add snow peas, ginger and tamari. Toss 1 min. Serve over quinoa.',
    ],
    tags: ['Light & Easy', 'Dinner'],
  },
  'LE-D5': {
    name: 'Pumpkin & Red Lentil Dhal with Brown Rice & Yoghurt',
    description: 'Deeply comforting. Butternut pumpkin in an Indian-inspired dhal.',
    imageUrl: IMG + 'pumpkin_red_lentil_dhal_with_brown_rice_yoghurt.png',
    blurhash: 'L6KTYu8{wI}?RO?HEMR+T#%LIVM}',
    cookTime: 30,
    prepTime: 5,
    servings: 1,
    calories: 460,
    ingredients: [
      { id: '1', name: 'Red lentils, rinsed', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '2', name: 'Butternut pumpkin, cubed', quantity: '1', unit: 'cup', category: 'dairy' },
      { id: '3', name: 'Tin diced tomatoes', quantity: '400', unit: 'g', category: 'produce' },
      { id: '4', name: 'Low-sodium veg/chicken stock', quantity: '1', unit: 'cup', category: 'meat' },
      { id: '5', name: 'Cumin', quantity: '0.5', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Coriander', quantity: '0.5', unit: 'tsp', category: 'produce' },
      { id: '7', name: 'Turmeric', quantity: '0.5', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Ginger + 1 garlic clove', quantity: '0.5', unit: 'tsp', category: 'produce' },
      { id: '9', name: 'Brown rice sachet', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '10', name: 'Yoghurt', quantity: '2', unit: 'tbsp', category: 'dairy' },
    ],
    instructions: [
      'Microwave rice 90 sec.',
      'Fry garlic + spices 30 sec. Add pumpkin. Add lentils, tomatoes, stock.',
      'Simmer 20–25 min until thick and tender. Serve over rice with yoghurt.',
    ],
    tags: ['Light & Easy', 'Dinner'],
  },
  'LE-D6': {
    name: 'Poached Ocean Trout with Asparagus & Millet',
    description: 'Ocean trout is a pink-fleshed sustainable fish. Poached gently for perfect texture.',
    imageUrl: IMG + 'poached_ocean_trout_with_asparagus_millet.png',
    blurhash: 'LRKduV~qk?x]?uWVRjofTMW=wHn$',
    cookTime: 30,
    prepTime: 5,
    servings: 1,
    calories: 460,
    ingredients: [
      { id: '1', name: 'Ocean trout fillet', quantity: '150', unit: 'g', category: 'pantry' },
      { id: '2', name: 'Asparagus', quantity: '1', unit: 'bunch', category: 'produce' },
      { id: '3', name: 'Millet', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '4', name: 'Water or low-sodium stock for poaching', quantity: '1', unit: 'cup', category: 'pantry' },
      { id: '5', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Fresh dill', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Cook millet in 1 cup water, boil then simmer covered 18 min.',
      'Bring poaching liquid to gentle simmer. Add trout. Cover, cook 8–10 min.',
      'Steam or boil asparagus 3–4 min.',
      'Plate millet, asparagus and trout. Drizzle olive oil and lemon.',
    ],
    tags: ['Light & Easy', 'Dinner'],
  },
  'LE-D7': {
    name: 'Slow-Cooked Chicken & Vegetable Casserole',
    description: 'Sunday comfort food. Chicken thighs become meltingly tender.',
    imageUrl: IMG + 'slow_cooked_chicken_vegetable_casserole.png',
    blurhash: 'LOK0$p?HyC%L~U%0WAs.Tex[ivV@',
    cookTime: 45,
    prepTime: 5,
    servings: 1,
    calories: 450,
    ingredients: [
      { id: '1', name: 'X skinless chicken thigh fillets', quantity: '2', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Medium sweet potato', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Carrots', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Celery sticks', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Low-sodium chicken stock', quantity: '1.5', unit: 'cups', category: 'meat' },
      { id: '6', name: 'Diced tomatoes', quantity: '0.5', unit: 'tin', category: 'produce' },
      { id: '7', name: 'Garlic clove', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Rosemary', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '9', name: 'Steamed green beans or broccolini', quantity: '1', unit: 'cup', category: 'produce' },
    ],
    instructions: [
      'Brown chicken thighs 2–3 min each side. Set aside.',
      'Fry garlic, carrots, celery 2 min.',
      'Add sweet potato, tomatoes, stock and herbs. Return chicken.',
      'Simmer covered 30–35 min until tender. Serve over steamed greens.',
    ],
    tags: ['Light & Easy', 'Dinner'],
  },
};

const GRAB_GO_BREAKFAST: CuratedRecipe = {
  name: 'Grab & go',
  description: 'No cooking — grab a quick option on your way out.',
  imageUrl: IMG + 'bircher_muesli_with_grated_apple_yoghurt.png',
  blurhash: 'LJKA$n~Wbwoz?bD*RjfQA0t8s+xa',
  cookTime: 0, prepTime: 0, servings: 1, calories: 0,
  ingredients: [], instructions: [], tags: ['Grab & Go', 'No Cook'],
};
const BUY_OUT_LUNCH: CuratedRecipe = {
  name: 'Buy out',
  description: 'No cooking — pick up a lunch out.',
  imageUrl: IMG + 'bircher_muesli_with_grated_apple_yoghurt.png',
  blurhash: 'LJKA$n~Wbwoz?bD*RjfQA0t8s+xa',
  cookTime: 0, prepTime: 0, servings: 1, calories: 0,
  ingredients: [], instructions: [], tags: ['Buy Out', 'No Cook'],
};
const BUY_OUT_DINNER: CuratedRecipe = {
  ...BUY_OUT_LUNCH,
  description: 'No cooking tonight — buy dinner out or order in. No groceries needed.',
};

const LIGHT_EASY_BANK: PlanBank = {
  recipes: RECIPES,
  breakfastWeekendCook: ['LE-B2', 'LE-B4', 'LE-B6'],
  breakfastWeekdayEasy: ['LE-B1', 'LE-B3', 'LE-B5', 'LE-B7'],
  lunchCook: ['LE-L1', 'LE-L2', 'LE-L3', 'LE-L4', 'LE-L5', 'LE-L6', 'LE-L7'],
  dinnersFresh: ['LE-D1', 'LE-D2', 'LE-D3', 'LE-D4', 'LE-D5', 'LE-D6', 'LE-D7'],
  batchMains: ['LE-D1', 'LE-D2', 'LE-D3', 'LE-D4', 'LE-D5', 'LE-D6', 'LE-D7', 'LE-L1', 'LE-L2', 'LE-L3', 'LE-L4', 'LE-L5', 'LE-L6', 'LE-L7'],
  grabGoBreakfast: GRAB_GO_BREAKFAST,
  buyOutLunch: BUY_OUT_LUNCH,
  buyOutDinner: BUY_OUT_DINNER,
};

export const LIGHT_EASY_MAX_BATCH_RECIPES = LIGHT_EASY_BANK.batchMains.length;

export function buildLightEasyMeals(
  durationDays: number,
  prefs: CookingPreferences = DEFAULT_COOKING_PREFS,
  startWeekday: number = 0,
): ScheduledMeal[] {
  return buildPlanMeals(LIGHT_EASY_BANK, durationDays, prefs, startWeekday);
}
