// ─────────────────────────────────────────────────────────────────────────
// Solo Active Professional — recipe bank + scheduling
//
// Recipes transcribed from the "4-Week Meal Plan Collection" (SP1- codes).
// Schedulable: feeds the shared plan engine (plan-engine.ts) exactly like
// High-Protein Simple, so the day-by-day browser and apply flow honour the
// user's Duration + cooking-style (batch / daily, leftovers, serving size).
// ─────────────────────────────────────────────────────────────────────────
import {
  buildPlanMeals,
  type CuratedRecipe,
  type PlanBank,
} from './plan-engine';
import {
  type CookingPreferences,
  type ScheduledMeal,
  DEFAULT_COOKING_PREFS,
} from './high-protein-plan';

const IMG =
  'https://wcjsrhdlnmfugdjtvadj.supabase.co/storage/v1/object/public/Solo%20Active%20Professional/';

const RECIPES: Record<string, CuratedRecipe> = {
  'SP1-B1': {
    name: 'Peanut Butter Banana Overnight Oats',
    description: 'Prep Sunday night in 3 min. Monday morning is grab-from-fridge.',
    imageUrl: IMG + 'peanut_butter_banana_overnight_oats.png',
    blurhash: 'LLI4hJ=^s:%L~VIURjt69ai^n3sl',
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    calories: 480,
    ingredients: [
      { id: '1', name: 'Rolled oats', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '2', name: 'Milk or oat milk', quantity: '0.75', unit: 'cup', category: 'dairy' },
      { id: '3', name: 'Peanut butter', quantity: '1', unit: 'tbsp', category: 'dairy' },
      { id: '4', name: 'Banana, sliced', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Honey', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Sprinkle chia seeds', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Sunday night: stir oats and milk in a jar. Seal and refrigerate.',
      'Morning: add banana, peanut butter, honey and chia. Eat from jar.',
    ],
    tags: ['Solo', 'Breakfast', 'No Cook'],
  },
  'SP1-B2': {
    name: 'Smashed Avo & Poached Egg on Sourdough',
    description: 'Australia\'s most iconic breakfast. Microwave-poaching saves 2 minutes.',
    imageUrl: IMG + 'smashed_avo_poached_egg_on_sourdough.png',
    blurhash: 'LIHUtc~B^+~VW@M{-o-:W[t7%Kxt',
    cookTime: 8,
    prepTime: 5,
    servings: 1,
    calories: 490,
    ingredients: [
      { id: '1', name: 'Sourdough bread', quantity: '2', unit: 'slices', category: 'bakery' },
      { id: '2', name: 'Ripe avocado', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Free-range eggs', quantity: '1', unit: 'whole', category: 'dairy' },
      { id: '4', name: 'Chilli flakes', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '5', name: 'Squeeze lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Black pepper', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Toast sourdough. Mash avocado with lemon and chilli.',
      'Microwave-poach egg: mug + 3 tbsp water, cover, 65–75 sec.',
      'Pile avo on toast. Top with egg.',
    ],
    tags: ['Solo', 'Breakfast', 'Quick'],
  },
  'SP1-B3': {
    name: 'Greek Yoghurt Protein Bowl with Berries & Granola',
    description: 'No cooking. High protein, high carb — ideal before a workout.',
    imageUrl: IMG + 'greek_yoghurt_protein_bowl_with_berries.png',
    blurhash: 'LPL|ox~q.8ja-5ITNGoftMV@Mdt6',
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    calories: 470,
    ingredients: [
      { id: '1', name: 'Plain Greek yoghurt', quantity: '0.75', unit: 'cup', category: 'dairy' },
      { id: '2', name: 'Frozen berries, microwaved 40 sec', quantity: '0.5', unit: 'cup', category: 'frozen' },
      { id: '3', name: 'Carmans 5-seed granola', quantity: '3', unit: 'tbsp', category: 'pantry' },
      { id: '4', name: 'Honey', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '5', name: 'Chia or hemp seeds', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: '1 scoop protein powder stirred in', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Microwave berries 40 sec.',
      'Spoon yoghurt into bowl. Top with berries, granola, honey and seeds.',
    ],
    tags: ['Solo', 'Breakfast', 'Quick'],
  },
  'SP1-B4': {
    name: 'Mango & Coconut Overnight Oats',
    description: 'Tropical variation. Different toppings keep overnight oats interesting mid-week.',
    imageUrl: IMG + 'mango_coconut_overnight_oats.png',
    blurhash: 'LRLNJN?ab{o3~VV@ayodI^R-Vrs+',
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    calories: 440,
    ingredients: [
      { id: '1', name: 'Rolled oats', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '2', name: 'Coconut or oat milk', quantity: '0.75', unit: 'cup', category: 'dairy' },
      { id: '3', name: 'Chia seeds', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '4', name: 'Honey', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: '1/4 cup mango chunks', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: '1 tbsp shredded coconut', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '7', name: 'Cinnamon', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Night before: stir oats, milk, chia and honey in jar. Refrigerate.',
      'Morning: add mango chunks, coconut and cinnamon. Eat from jar.',
    ],
    tags: ['Solo', 'Breakfast', 'No Cook'],
  },
  'SP1-B5': {
    name: 'Protein Smoothie Bowl',
    description: 'Friday energy blast. Thick enough to eat with a spoon.',
    imageUrl: IMG + 'protein_smoothie_bowl.png',
    blurhash: 'LCKdPU00PBwe}=~pX7IUcrofVEtR',
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    calories: 480,
    ingredients: [
      { id: '1', name: 'Frozen banana', quantity: '1', unit: 'whole', category: 'frozen' },
      { id: '2', name: 'Frozen berries', quantity: '0.5', unit: 'cup', category: 'frozen' },
      { id: '3', name: 'Greek yoghurt', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { id: '4', name: 'Oat milk', quantity: '0.25', unit: 'cup', category: 'dairy' },
      { id: '5', name: '1 scoop vanilla protein powder', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '6', name: 'Granola', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '7', name: 'Chia seeds', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '8', name: 'Fresh berries', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '9', name: 'Honey', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Blend banana, berries, yoghurt and oat milk until very thick.',
      'Pour into bowl. Top with granola, chia, berries and honey.',
    ],
    tags: ['Solo', 'Breakfast', 'Quick'],
  },
  'SP1-B6': {
    name: 'Big Brekkie Frittata (Single Serve)',
    description: 'A solo frittata — same effort as scrambled eggs, much more impressive.',
    imageUrl: IMG + 'big_brekkie_frittata_single_serve.png',
    blurhash: 'LDK^pR~WyEx[E1IUIAjEt.S1R5r@',
    cookTime: 14,
    prepTime: 5,
    servings: 1,
    calories: 540,
    ingredients: [
      { id: '1', name: 'Free-range eggs', quantity: '3', unit: 'whole', category: 'dairy' },
      { id: '2', name: 'Button mushrooms, sliced', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Baby spinach', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '4', name: 'Cherry tomatoes, halved', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Grated cheese', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { id: '6', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '7', name: 'Salt, pepper, chilli flakes', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Preheat oven grill/broiler to high.',
      'Heat oil in small oven-safe pan. Add mushrooms 2 min, spinach and tomatoes 1 min.',
      'Whisk eggs with salt/pepper. Pour over veg. Scatter cheese.',
      'Stovetop 2 min until edges set. Under grill 3–4 min until puffed and golden.',
      'Lunches',
    ],
    tags: ['Solo', 'Breakfast'],
  },
  'SP1-L1': {
    name: 'Honey Soy Chicken Rice Bowl (leftover)',
    description: 'Yesterday\'s honey soy chicken transforms into today\'s rice bowl. Add fresh cucumber and sriracha.',
    imageUrl: IMG + 'honey_soy_chicken_rice_bowl_leftover.png',
    blurhash: 'LDF$6DIA0g%g.T%L%0R+I[S5%1aJ',
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    calories: 550,
    ingredients: [
      { id: '1', name: 'Leftover honey soy chicken thighs, sliced', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Leftover brown rice', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '3', name: 'Cucumber, sliced', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Handful baby spinach', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Sriracha or sweet chilli sauce', quantity: '1', unit: 'tbsp', category: 'produce' },
      { id: '6', name: 'Sesame seeds', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Reheat rice 90 sec. Reheat chicken 60–90 sec.',
      'Assemble bowl: rice, spinach, cucumber, chicken on top.',
      'Drizzle sriracha. Sprinkle sesame seeds.',
    ],
    tags: ['Solo', 'Lunch', 'No Cook'],
  },
  'SP1-L2': {
    name: 'Prawn Noodle Stir-Fry (leftover tiffin)',
    description: 'Cold noodle stir-fry is excellent — flavours intensify overnight.',
    imageUrl: IMG + 'prawn_noodle_stir_fry_leftover_tiffin.png',
    blurhash: 'LGIg$C^jyDxu*0IqIBR+16bciw$%',
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    calories: 550,
    ingredients: [
      { id: '1', name: 'Leftover prawn hokkien noodle stir-fry', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Extra splash soy sauce', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '3', name: 'Fresh lime wedge', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Microwave 90 sec if heating, or eat cold.',
      'Add lime and extra soy if needed.',
    ],
    tags: ['Solo', 'Lunch', 'No Cook'],
  },
  'SP1-L3': {
    name: 'Salmon & Sweet Potato Tiffin Bowl',
    description: 'Tuesday\'s salmon over sweet potato wedges. Tahini transforms the whole thing.',
    imageUrl: IMG + 'salmon_sweet_potato_tiffin_bowl.png',
    blurhash: 'LJJtk,9ZS5t6~VxaMykB%zVsVst7',
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    calories: 540,
    ingredients: [
      { id: '1', name: 'Leftover salmon fillet, flaked', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Leftover sweet potato wedges', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Large handful baby spinach', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Tahini', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '5', name: 'Lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Water', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '7', name: 'Sprinkle pepitas', quantity: '1', unit: 'whole', category: 'bakery' },
    ],
    instructions: [
      'Arrange spinach, sweet potato and flaked salmon in container.',
      'Mix tahini dressing separately. Drizzle before eating.',
      'Add pepitas for crunch.',
    ],
    tags: ['Solo', 'Lunch', 'Quick'],
  },
  'SP1-L4': {
    name: 'Wednesday Taco Mince Tiffin Bowl',
    description: 'The taco mince is even better the next day — spices deepen overnight.',
    imageUrl: IMG + 'wednesday_taco_mince_tiffin.png',
    blurhash: 'LGJkWKE2%$-T-q%MS1M{.TaJRONf',
    cookTime: 2,
    prepTime: 5,
    servings: 1,
    calories: 560,
    ingredients: [
      { id: '1', name: 'Leftover taco mince', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Black beans', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '3', name: 'Leftover rice', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '4', name: 'Fresh spinach or shredded lettuce', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Salsa, coriander, lime wedge', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Reheat mince and rice 90 sec.',
      'Top with fresh lettuce, coriander and lime.',
    ],
    tags: ['Solo', 'Lunch', 'Quick'],
  },
  'SP1-L5': {
    name: 'Barramundi Rice Bowl (leftover tiffin)',
    description: 'Flake barramundi over leftover rice. Add rocket and lemon.',
    imageUrl: IMG + 'barramundi_rice_bowl_leftover.png',
    blurhash: 'LCI}O-?b58Mx?w~WIAM{KRxbwHod',
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    calories: 530,
    ingredients: [
      { id: '1', name: 'Leftover barramundi fillet, flaked', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Leftover rice or noodles', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '3', name: 'Handful rocket or mixed leaves', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Lemon', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Olive oil or sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Black pepper', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Flake barramundi over rice.',
      'Add rocket. Drizzle olive oil and lemon. Season.',
      'Eat cold or reheat 60 sec (without the leaves).',
      'Dinners',
    ],
    tags: ['Solo', 'Lunch', 'No Cook'],
  },
  'SP1-D1': {
    name: 'Honey Soy Chicken Thigh Bowl',
    description: 'Australia\'s most-cooked weeknight protein bowl. Make double — tomorrow\'s lunch sorted.',
    imageUrl: IMG + 'honey_soy_chicken_thigh_bowl.png',
    blurhash: 'LULD+3.7yExv_NV[WBoLPCn,R5e.',
    cookTime: 22,
    prepTime: 5,
    servings: 1,
    calories: 680,
    ingredients: [
      { id: '1', name: 'Chicken thigh fillets', quantity: '2', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Honey', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '3', name: 'Low-sodium soy', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '4', name: 'Sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Garlic clove', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Cooked brown rice', quantity: '0.75', unit: 'cup', category: 'pantry' },
      { id: '7', name: 'Broccolini, steamed 2 min', quantity: '200', unit: 'g', category: 'produce' },
      { id: '8', name: 'Sesame seeds', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '9', name: 'Spring onion', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Mix glaze. Coat chicken.',
      'Pan-fry chicken 5–6 min per side until caramelised. Rest, slice.',
      'Microwave rice 90 sec. Steam broccolini 2 min.',
      'Serve chicken over rice and broccolini. Drizzle pan glaze.',
    ],
    tags: ['Solo', 'Dinner'],
  },
  'SP1-D2': {
    name: 'Garlic Prawn Stir-Fry with Hokkien Noodles',
    description: 'Prawn stir-fry: 90-second cooking time means it\'s nearly impossible to make slowly.',
    imageUrl: IMG + 'garlic_prawn_stir_fry_with_hokkien_noodles.png',
    blurhash: 'LVKmti?HyDbv?aaeRkaep{bcV@sn',
    cookTime: 20,
    prepTime: 5,
    servings: 1,
    calories: 650,
    ingredients: [
      { id: '1', name: 'Frozen prawn meat, defrosted', quantity: '150', unit: 'g', category: 'frozen' },
      { id: '2', name: 'Fresh hokkien noodles', quantity: '200', unit: 'g', category: 'pantry' },
      { id: '3', name: 'Soy', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '4', name: 'Oyster sauce', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Garlic cloves', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Chilli flakes', quantity: '0.5', unit: 'tsp', category: 'produce' },
      { id: '8', name: 'Bok choy or pak choy', quantity: '1', unit: 'cup', category: 'produce' },
    ],
    instructions: [
      'Soak noodles in boiling water 2 min. Drain.',
      'Heat wok on HIGH. Garlic + chilli 30 sec. Add prawns 90 sec per side.',
      'Add bok choy 2 min. Add noodles + sauces. Toss 1 min.',
      'SAVE HALF for tomorrow\'s tiffin.',
    ],
    tags: ['Solo', 'Dinner'],
  },
  'SP1-D3': {
    name: 'Pan-Seared Salmon with Sweet Potato & Greens',
    description: 'Honey soy glazed salmon with air-fried sweet potato wedges.',
    imageUrl: IMG + 'pan_seared_salmon_with_sweet_potato_greens.png',
    blurhash: 'LLJacf~qKktR?ve-t7S#GcIo#kxZ',
    cookTime: 22,
    prepTime: 5,
    servings: 1,
    calories: 680,
    ingredients: [
      { id: '1', name: 'Salmon fillet', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Small sweet potato, cut into wedges', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Honey', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '4', name: 'Soy', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '5', name: 'Sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Baby spinach or broccolini', quantity: '1', unit: 'cup', category: 'produce' },
      { id: '7', name: 'Lemon wedge', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
    ],
    instructions: [
      'Preheat air fryer 200C (or oven 220C). Toss sweet potato in oil. Cook 18 min.',
      'Mix glaze. Coat salmon.',
      'Pan medium-high: salmon skin-down 4 min. Flip, baste 3 min.',
      'Wilt spinach in same pan 30 sec.',
      'Plate sweet potato, greens, salmon. Squeeze lemon.',
    ],
    tags: ['Solo', 'Dinner'],
  },
  'SP1-D4': {
    name: 'Beef/Turkey Taco Bowl with Black Beans',
    description: 'Taco bowl: top-trending weeknight meal across Australia and NZ.',
    imageUrl: IMG + 'beef_turkey_taco_bowl_with_black_beans.png',
    blurhash: 'LLHBF}-osoxY_NNHIpWBItaxWAM}',
    cookTime: 25,
    prepTime: 5,
    servings: 1,
    calories: 700,
    ingredients: [
      { id: '1', name: 'Lean beef mince OR turkey mince', quantity: '150', unit: 'g', category: 'meat' },
      { id: '2', name: 'Black beans , rinsed', quantity: '0.5', unit: 'tin', category: 'pantry' },
      { id: '3', name: 'Frozen corn', quantity: '0.5', unit: 'cup', category: 'frozen' },
      { id: '4', name: 'Cumin', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Paprika', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Garlic powder', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '7', name: 'Cooked rice', quantity: '0.75', unit: 'cup', category: 'pantry' },
      { id: '8', name: 'Sour cream', quantity: '1', unit: 'tbsp', category: 'dairy' },
      { id: '9', name: 'Salsa', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '10', name: 'Lettuce', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Coriander', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '12', name: 'Lime', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Fry mince 5–6 min. Add spices 1 min. Add beans and corn 3 min.',
      'Serve over rice. Top with sour cream, salsa, lettuce, coriander, lime.',
      'MAKE EXTRA mince for tomorrow\'s tiffin.',
    ],
    tags: ['Solo', 'Dinner'],
  },
  'SP1-D5': {
    name: 'Soy Ginger Barramundi with Stir-Fry Greens',
    description: 'Barramundi is Australia\'s native sustainable fish — mild and foolproof.',
    imageUrl: IMG + 'soy_ginger_barramundi_with_stir_fry_greens.png',
    blurhash: 'LLJ@zW~p.9-;~Vt6M{t6yYt8VrjE',
    cookTime: 18,
    prepTime: 5,
    servings: 1,
    calories: 600,
    ingredients: [
      { id: '1', name: 'Barramundi fillet', quantity: '1', unit: 'whole', category: 'meat' },
      { id: '2', name: 'Soy', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '3', name: 'Grated ginger', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '4', name: 'Honey', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Asian greens', quantity: '1', unit: 'cup', category: 'pantry' },
      { id: '6', name: 'Sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '7', name: 'Garlic clove', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Cooked rice or noodles', quantity: '0.5', unit: 'cup', category: 'pantry' },
    ],
    instructions: [
      'Mix soy, ginger and honey.',
      'Pan medium-high: barramundi skin-down 4 min. Flip, pour glaze, cook 3 min.',
      'Wilt greens with garlic and sesame oil 2 min.',
      'Serve over rice/noodles.',
    ],
    tags: ['Solo', 'Dinner'],
  },
  'SP1-D6': {
    name: 'Chicken Shawarma Bowl',
    description: 'Shawarma-spiced chicken is having a major moment in Australian home kitchens.',
    imageUrl: IMG + 'chicken_shawarma_bowl.png',
    blurhash: 'L7K,+_0056?a:NtRRjIU.TWBQ-xb',
    cookTime: 28,
    prepTime: 5,
    servings: 1,
    calories: 720,
    ingredients: [
      { id: '1', name: 'Chicken thigh fillets', quantity: '180', unit: 'g', category: 'meat' },
      { id: '2', name: 'Cumin', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '3', name: 'Coriander', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '4', name: 'Paprika', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Turmeric', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Garlic powder', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '7', name: 'Olive oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Juice 1/2 lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '9', name: 'Garlic yoghurt: 2 tbsp Greek yoghurt', quantity: '1', unit: 'whole', category: 'dairy' },
      { id: '10', name: 'Garlic clove grated', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Rice or flatbread', quantity: '1', unit: 'whole', category: 'bakery' },
      { id: '12', name: 'Shredded lettuce, tomato, cucumber, parsley', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Mix spices, oil and lemon. Coat chicken. Marinate 5–10 min.',
      'Pan-fry 5–6 min per side until charred and cooked. Rest 2 min, slice thin.',
      'Make garlic yoghurt.',
      'Serve over rice or roll in flatbread with salad and garlic sauce.',
    ],
    tags: ['Solo', 'Dinner'],
  },
  'SP1-D7': {
    name: 'Mince Bolognese with Rigatoni (single serve)',
    description: 'A proper rich bolognese. Cook enough sauce for two nights.',
    imageUrl: IMG + 'mince_bolognese_with_rigatoni.png',
    blurhash: 'L7HK@800*0-700?HD%NH0LVtDOT0',
    cookTime: 28,
    prepTime: 5,
    servings: 1,
    calories: 730,
    ingredients: [
      { id: '1', name: 'Beef mince OR turkey mince', quantity: '150', unit: 'g', category: 'meat' },
      { id: '2', name: 'Rigatoni or spaghetti', quantity: '100', unit: 'g', category: 'pantry' },
      { id: '3', name: 'Crushed tomatoes', quantity: '0.5', unit: 'tin', category: 'produce' },
      { id: '4', name: 'Onion diced + 2 garlic cloves + 1 tsp oregano', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Onion diced + 2 garlic cloves + 1 tsp basil', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Tomato paste', quantity: '1', unit: 'tbsp', category: 'produce' },
      { id: '7', name: 'Olive oil', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '8', name: 'Worcestershire sauce', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '9', name: 'Parmesan', quantity: '1', unit: 'whole', category: 'dairy' },
      { id: '10', name: 'Fresh basil', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Boil pasta per packet in salted water.',
      'Fry onion 3 min, garlic 1 min. Brown mince 4–5 min.',
      'Add tomato paste, tomatoes, Worcestershire, herbs. Simmer 12–15 min.',
      'Toss with pasta. Serve with parmesan and basil.',
    ],
    tags: ['Solo', 'Dinner'],
  },
};

const GRAB_GO_BREAKFAST: CuratedRecipe = {
  name: 'Grab & go',
  description: 'No cooking — grab a quick option on your way out.',
  imageUrl: IMG + 'peanut_butter_banana_overnight_oats.png',
  blurhash: 'LLI4hJ=^s:%L~VIURjt69ai^n3sl',
  cookTime: 0, prepTime: 0, servings: 1, calories: 0,
  ingredients: [], instructions: [], tags: ['Grab & Go', 'No Cook'],
};
const BUY_OUT_LUNCH: CuratedRecipe = {
  name: 'Buy out',
  description: 'No cooking — pick up a lunch out.',
  imageUrl: IMG + 'peanut_butter_banana_overnight_oats.png',
  blurhash: 'LLI4hJ=^s:%L~VIURjt69ai^n3sl',
  cookTime: 0, prepTime: 0, servings: 1, calories: 0,
  ingredients: [], instructions: [], tags: ['Buy Out', 'No Cook'],
};
const BUY_OUT_DINNER: CuratedRecipe = {
  ...BUY_OUT_LUNCH,
  description: 'No cooking tonight — buy dinner out or order in. No groceries needed.',
};

const SOLO_ACTIVE_BANK: PlanBank = {
  recipes: RECIPES,
  breakfastWeekendCook: ['SP1-B2', 'SP1-B6'],
  breakfastWeekdayEasy: ['SP1-B1', 'SP1-B3', 'SP1-B4', 'SP1-B5'],
  lunchCook: ['SP1-L1', 'SP1-L2', 'SP1-L3', 'SP1-L4', 'SP1-L5', 'SP1-L1', 'SP1-L2'],
  dinnersFresh: ['SP1-D1', 'SP1-D2', 'SP1-D3', 'SP1-D4', 'SP1-D5', 'SP1-D6', 'SP1-D7'],
  batchMains: ['SP1-D1', 'SP1-D2', 'SP1-D3', 'SP1-D4', 'SP1-D5', 'SP1-D6', 'SP1-D7', 'SP1-L1', 'SP1-L2', 'SP1-L3', 'SP1-L4', 'SP1-L5'],
  grabGoBreakfast: GRAB_GO_BREAKFAST,
  buyOutLunch: BUY_OUT_LUNCH,
  buyOutDinner: BUY_OUT_DINNER,
};

export const SOLO_ACTIVE_MAX_BATCH_RECIPES = SOLO_ACTIVE_BANK.batchMains.length;

export function buildSoloActiveMeals(
  durationDays: number,
  prefs: CookingPreferences = DEFAULT_COOKING_PREFS,
  startWeekday: number = 0,
): ScheduledMeal[] {
  return buildPlanMeals(SOLO_ACTIVE_BANK, durationDays, prefs, startWeekday);
}
