// ─────────────────────────────────────────────────────────────────────────
// Vegetarian Delight — recipe bank + scheduling
//
// Recipes transcribed from the "4-Week Meal Plan Collection" (VG- codes). The
// plan is SCHEDULABLE: it feeds the shared plan engine (plan-engine.ts) exactly
// like High-Protein Simple, so the day-by-day browser and the apply flow honour
// the user's Duration + cooking-style (batch / daily, leftovers, serving size).
// ─────────────────────────────────────────────────────────────────────────
import {
  buildPlanMeals,
  type CuratedRecipe,
  type PlanBank,
} from './plan-engine';
import {
  type CookingPreferences,
  type ScheduledMeal,
  DEFAULT_COOKING_PREFS,
} from './high-protein-plan';

const IMG =
  'https://wcjsrhdlnmfugdjtvadj.supabase.co/storage/v1/object/public/Vegeterian%20Delight%20Meal%20Plan/';

// ── Recipe bank (keyed by the doc's VG- codes) ──
const RECIPES: Record<string, CuratedRecipe> = {
  'VG-B1': {
    name: 'Shakshuka for Two',
    description: 'Most-saved weekend brunch recipe in Australia. Eggs in spiced tomato — one pan, 14 min.',
    imageUrl: IMG + 'shakshuka_for_two.png',
    blurhash: 'LJHBxe0Ko}a}?wt7RPoL%$aKaKt6',
    cookTime: 14,
    prepTime: 5,
    servings: 2,
    calories: 480,
    ingredients: [
      { id: '1', name: 'Free-range eggs', quantity: '4', unit: 'whole', category: 'dairy' },
      { id: '2', name: 'Tin crushed tomatoes', quantity: '400', unit: 'g', category: 'produce' },
      { id: '3', name: 'Large onion', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Garlic cloves', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Smoked paprika', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Ground cumin', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '7', name: 'Chilli flakes', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '8', name: 'Olive oil', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '9', name: 'Crumbled feta', quantity: '100', unit: 'g', category: 'dairy' },
      { id: '10', name: 'Fresh herbs', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Crusty sourdough', quantity: '4', unit: 'slices', category: 'bakery' },
    ],
    instructions: [
      'Heat oil. Fry onion 3–4 min. Add garlic and spices 1 min.',
      'Add tomatoes. Simmer 4–5 min.',
      'Make 4 wells. Crack eggs in. Cover, cook 4–5 min.',
      'Scatter feta and herbs. Serve from pan with sourdough.',
    ],
    tags: ['Vegetarian', 'Breakfast'],
  },
  'VG-B2': {
    name: 'Mixed Berry Chia Overnight Oats',
    description: 'Prep two jars Sunday night. Monday morning is grab-from-fridge.',
    imageUrl: IMG + 'mixed_berry_chia_overnight_oats.png',
    blurhash: 'LEHUwi~V%MxZnMITs:xtScxaVsae',
    cookTime: 0,
    prepTime: 5,
    servings: 2,
    calories: 440,
    ingredients: [
      { id: '1', name: 'Rolled oats', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '2', name: 'Greek yoghurt', quantity: '0.75', unit: 'cup', category: 'dairy' },
      { id: '3', name: 'Oat milk', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { id: '4', name: 'Chia seeds', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '5', name: 'Honey', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: 'Mixed berries', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '7', name: 'Granola', quantity: '1', unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Sunday night: mix oats, yoghurt, milk, chia, honey in jars. Refrigerate.',
      'Monday: add berries and granola. Eat from jar.',
    ],
    tags: ['Vegetarian', 'Breakfast', 'No Cook'],
  },
  'VG-B3': {
    name: 'Tropical Smoothie Bowl with Hemp Seeds & Granola',
    description: '5-minute no-cook bowl. Mango and banana make the perfect tropical base.',
    imageUrl: IMG + 'tropical_smoothie_bowl_with_hemp_seeds.png',
    blurhash: 'LMLNA1_3%h%M~BD%M|jspIaMRONG',
    cookTime: 5,
    prepTime: 5,
    servings: 2,
    calories: 460,
    ingredients: [
      { id: '1', name: 'Frozen mango chunks', quantity: '1.5', unit: 'cups', category: 'frozen' },
      { id: '2', name: 'Large frozen banana', quantity: '1', unit: 'whole', category: 'frozen' },
      { id: '3', name: 'Greek yoghurt', quantity: '0.75', unit: 'cup', category: 'dairy' },
      { id: '4', name: 'Oat milk', quantity: '0.25', unit: 'cup', category: 'dairy' },
      { id: '5', name: 'Granola', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '6', name: 'Hemp seeds', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '7', name: 'Kiwi', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Shredded coconut', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '9', name: 'Honey', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Blend mango, banana, yoghurt and oat milk until very thick.',
      'Divide into 2 bowls.',
      'Top with granola, hemp seeds, kiwi, coconut and honey.',
    ],
    tags: ['Vegetarian', 'Breakfast', 'Quick'],
  },
  'VG-B4': {
    name: 'Vegemite & Avo Toast with Dukkah-Spiced Egg',
    description: 'The Aussie classic elevated with dukkah — a Middle Eastern nut-spice blend.',
    imageUrl: IMG + 'vegemite_avo_toast_with_dukkah_spiced_egg.png',
    blurhash: 'L8IOIR%3X;xv?Z00D%oet:4nMbk7',
    cookTime: 8,
    prepTime: 5,
    servings: 2,
    calories: 450,
    ingredients: [
      { id: '1', name: 'Wholegrain bread', quantity: '4', unit: 'slices', category: 'bakery' },
      { id: '2', name: 'Ripe avocados', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Free-range eggs', quantity: '2', unit: 'whole', category: 'dairy' },
      { id: '4', name: 'Vegemite', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '5', name: 'Dukkah', quantity: '2', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Chilli flakes', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Toast bread. Mash avocado with lemon and pepper.',
      'Microwave-poach each egg: mug + 3 tbsp water, cover, 65–75 sec.',
      'Spread Vegemite on toast. Pile on avo. Slide egg on top.',
      'Sprinkle dukkah generously.',
    ],
    tags: ['Vegetarian', 'Breakfast', 'Quick'],
  },
  'VG-B5': {
    name: 'Bircher Muesli with Apple & Toasted Walnuts',
    description: 'Classic Swiss-meets-Australian brekkie. Prep the night before — creamy without cooking.',
    imageUrl: IMG + 'bircher_muesli_with_apple_toasted_walnuts.png',
    blurhash: 'LSL;Ke_2bwxu~qM|RjofI[tRs8Rj',
    cookTime: 0,
    prepTime: 5,
    servings: 2,
    calories: 430,
    ingredients: [
      { id: '1', name: 'Rolled oats', quantity: '1', unit: 'cup', category: 'pantry' },
      { id: '2', name: 'Greek yoghurt per serve', quantity: '0.75', unit: 'cup', category: 'dairy' },
      { id: '3', name: 'Apple juice per serve', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '4', name: 'Apple, grated', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Honey', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: 'Toasted walnuts', quantity: '0.25', unit: 'cup', category: 'bakery' },
      { id: '7', name: 'Cinnamon', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Night before: mix oats, yoghurt, apple juice, grated apple, honey in 2 jars.',
      'Morning: stir, top with walnuts and cinnamon.',
    ],
    tags: ['Vegetarian', 'Breakfast', 'No Cook'],
  },
  'VG-B6': {
    name: 'Greek Yoghurt Parfait with Granola & Strawberries',
    description: 'Layered in a glass — looks like a cafe parfait. Zero cooking.',
    imageUrl: IMG + 'greek_yoghurt_parfait_with_granola_strawberries.png',
    blurhash: 'L8HL3l~V01I;57D%9GM{9uR+^i-p',
    cookTime: 2,
    prepTime: 5,
    servings: 2,
    calories: 420,
    ingredients: [
      { id: '1', name: 'Plain Greek yoghurt per serve', quantity: '0.75', unit: 'cup', category: 'dairy' },
      { id: '2', name: 'Carmans 5-seed granola per serve', quantity: '4', unit: 'tbsp', category: 'pantry' },
      { id: '3', name: 'Strawberries per serve, sliced', quantity: '0.5', unit: 'cup', category: 'produce' },
      { id: '4', name: 'Honey', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '5', name: 'Vanilla extract', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '6', name: 'Hemp or chia seeds', quantity: '1', unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Stir vanilla into yoghurt if using.',
      'Layer in glass: yoghurt → granola → strawberries → repeat.',
      'Top with honey and seeds.',
    ],
    tags: ['Vegetarian', 'Breakfast', 'Quick'],
  },
  'VG-B7': {
    name: 'Herb & Feta Frittata with Baby Spinach',
    description: 'Fluffy golden eggs with feta and herbs. Weekend-worthy one-pan brekkie.',
    imageUrl: IMG + 'herb_feta_frittata_with_baby_spinach.png',
    blurhash: 'LDJHms~pyF?G9h9FM_RjAf-;rWS5',
    cookTime: 14,
    prepTime: 5,
    servings: 2,
    calories: 490,
    ingredients: [
      { id: '1', name: 'Free-range eggs', quantity: '6', unit: 'whole', category: 'dairy' },
      { id: '2', name: 'Feta, crumbled', quantity: '80', unit: 'g', category: 'dairy' },
      { id: '3', name: 'Baby spinach', quantity: '2', unit: 'cups', category: 'produce' },
      { id: '4', name: 'Cherry tomatoes, halved', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Button mushrooms, sliced', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Milk', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { id: '7', name: 'Fresh dill or parsley', quantity: '1', unit: 'tbsp', category: 'produce' },
      { id: '8', name: 'Olive oil', quantity: '1', unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Preheat grill to high.',
      'Heat oil in oven-safe pan. Add mushrooms 2 min, spinach 1 min.',
      'Whisk eggs with milk and herbs. Pour over veg. Add tomatoes and feta.',
      'Stovetop 3 min until edges set. Under grill 4–5 min until puffed and golden.',
      'Lunches',
    ],
    tags: ['Vegetarian', 'Breakfast'],
  },
  'VG-D1': {
    name: 'Halloumi & Roasted Vegetable Tray Bake with Quinoa',
    description: 'One of the most-pinned vegetarian dinners in Australia. Golden halloumi over roasted veg.',
    imageUrl: IMG + 'halloumi_roasted_vegetable_tray_bake_with_quinoa.png',
    blurhash: 'LSLDMe={tlxa~pS4RjbaBpS5Vsof',
    cookTime: 22,
    prepTime: 5,
    servings: 2,
    calories: 620,
    ingredients: [
      { id: '1', name: 'Halloumi, sliced 1cm', quantity: '250', unit: 'g', category: 'dairy' },
      { id: '2', name: 'Zucchini', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Cherry tomatoes', quantity: '1', unit: 'cup', category: 'produce' },
      { id: '4', name: 'Red capsicum', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Red onion', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Olive oil', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '7', name: 'Oregano', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Garlic powder', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '9', name: 'Dry quinoa → cook with 1.5 cups water', quantity: '0.75', unit: 'cup', category: 'pantry' },
      { id: '10', name: 'Handful rocket', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Balsamic glaze', quantity: '1', unit: 'tbsp', category: 'pantry' },
    ],
    instructions: [
      'Preheat oven 220C. Toss veg in oil, oregano, garlic. Roast 15 min.',
      'Cook quinoa: boil then simmer covered 12 min. Fluff.',
      'Push veg to edges. Add halloumi to tray. Roast 5–6 min until golden.',
      'Serve over quinoa with rocket and balsamic glaze.',
    ],
    tags: ['Vegetarian', 'Dinner'],
  },
  'VG-D2': {
    name: 'Coconut Red Lentil Dhal with Brown Rice & Naan',
    description: 'One of the most beloved vegetarian dinners in both Australia and NZ.',
    imageUrl: IMG + 'coconut_red_lentil_dhal_with_brown_rice_naan.png',
    blurhash: 'LMI#AN~WTL%g?vt7V@V[BYo}xVV@',
    cookTime: 25,
    prepTime: 5,
    servings: 2,
    calories: 580,
    ingredients: [
      { id: '1', name: 'Red lentils, rinsed', quantity: '1', unit: 'cup', category: 'pantry' },
      { id: '2', name: 'X 400ml tin coconut milk', quantity: '1', unit: 'whole', category: 'dairy' },
      { id: '3', name: 'Tin crushed tomatoes', quantity: '400', unit: 'g', category: 'produce' },
      { id: '4', name: 'Small onion', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Garlic cloves', quantity: '3', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Grated ginger', quantity: '1', unit: 'tbsp', category: 'produce' },
      { id: '7', name: 'Garam masala', quantity: '1.5', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Cumin', quantity: '1.5', unit: 'tsp', category: 'pantry' },
      { id: '9', name: 'Turmeric', quantity: '1.5', unit: 'tsp', category: 'pantry' },
      { id: '10', name: 'Brown rice', quantity: '0.75', unit: 'cup', category: 'pantry' },
      { id: '11', name: 'Mini naan', quantity: '2', unit: 'whole', category: 'bakery' },
      { id: '12', name: 'Fresh coriander', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '13', name: 'Lemon', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Fry onion 3 min. Add garlic, ginger, spices 1 min.',
      'Add lentils, tomatoes, coconut milk. Stir. Simmer 18–20 min until thick.',
      'Microwave rice + warm naan.',
      'Serve dhal over rice with naan, coriander and lemon.',
    ],
    tags: ['Vegetarian', 'Dinner'],
  },
  'VG-D3': {
    name: 'Pasta Primavera with Asparagus, Peas & Lemon Ricotta',
    description: 'Pasta primavera is having a massive resurgence in Australian home cooking.',
    imageUrl: IMG + 'pasta_primavera_with_asparagus_peas_lemon_ricotta.png',
    blurhash: 'LGMQeL_2%O%3~VDjM{jF.AM|M^aw',
    cookTime: 25,
    prepTime: 5,
    servings: 2,
    calories: 620,
    ingredients: [
      { id: '1', name: 'Linguine or spaghetti', quantity: '200', unit: 'g', category: 'pantry' },
      { id: '2', name: 'Asparagus, cut into 3cm pieces', quantity: '1', unit: 'bunch', category: 'produce' },
      { id: '3', name: 'Frozen peas', quantity: '1', unit: 'cup', category: 'frozen' },
      { id: '4', name: 'Fresh ricotta per serve', quantity: '2', unit: 'tbsp', category: 'dairy' },
      { id: '5', name: 'Juice', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '6', name: 'Zest 1 lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Garlic cloves', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Olive oil', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '9', name: 'Grated parmesan', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { id: '10', name: 'Fresh mint or basil', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Cook pasta in salted water. Add asparagus last 2 min, peas last 1 min.',
      'Reserve 1/2 cup pasta water. Drain.',
      'Heat oil + garlic 1 min. Return pasta and veg.',
      'Add lemon juice, zest, pasta water. Toss with parmesan.',
      'Serve topped with a dollop of ricotta and fresh herbs.',
    ],
    tags: ['Vegetarian', 'Dinner'],
  },
  'VG-D4': {
    name: 'Saag Paneer with Basmati Rice',
    description: 'Most popular Indian vegetarian curry across Australian restaurants and home kitchens.',
    imageUrl: IMG + 'saag_paneer_with_basmati_rice.png',
    blurhash: 'LXMQbF-:xu%M~pV[M{f6%NogV?Rj',
    cookTime: 28,
    prepTime: 5,
    servings: 2,
    calories: 640,
    ingredients: [
      { id: '1', name: 'Paneer , cubed', quantity: '200', unit: 'g', category: 'dairy' },
      { id: '2', name: 'Baby spinach', quantity: '300', unit: 'g', category: 'produce' },
      { id: '3', name: 'Onion', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Garlic cloves', quantity: '3', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Grated ginger', quantity: '1', unit: 'tbsp', category: 'produce' },
      { id: '6', name: 'Garam masala', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '7', name: 'Cumin', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Coriander', quantity: '1', unit: 'tsp', category: 'produce' },
      { id: '9', name: 'Turmeric', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '10', name: 'Greek yoghurt', quantity: '3', unit: 'tbsp', category: 'dairy' },
      { id: '11', name: 'Ghee or olive oil', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '12', name: 'Basmati rice, rinsed', quantity: '0.75', unit: 'cup', category: 'pantry' },
    ],
    instructions: [
      'Start rice: 3/4 cup + 1.5 cups water, boil then simmer 12 min.',
      'Fry paneer cubes 2–3 min per side until golden. Set aside.',
      'Fry onion 3 min. Add garlic, ginger, spices 1 min. Add spinach in handfuls 3 min.',
      'Add yoghurt + 3 tbsp water. Simmer 3 min. Return paneer 2 min.',
      'Serve over rice.',
    ],
    tags: ['Vegetarian', 'Dinner'],
  },
  'VG-D5': {
    name: 'Egg Fried Rice with Edamame & Corn',
    description: 'Egg fried rice: Australia\'s most-cooked weeknight dinner in the vegetarian version.',
    imageUrl: IMG + 'egg_fried_rice_with_edamame_corn.png',
    blurhash: 'LIMjaJ~p%hxu~UNGM_oItTkDRNob',
    cookTime: 18,
    prepTime: 5,
    servings: 2,
    calories: 580,
    ingredients: [
      { id: '1', name: 'Cooked day-old jasmine rice', quantity: '2', unit: 'cups', category: 'pantry' },
      { id: '2', name: 'Eggs, whisked', quantity: '4', unit: 'whole', category: 'dairy' },
      { id: '3', name: 'Frozen edamame, microwaved 2 min', quantity: '1', unit: 'cup', category: 'frozen' },
      { id: '4', name: 'Frozen corn', quantity: '0.5', unit: 'cup', category: 'frozen' },
      { id: '5', name: 'Spring onions', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Garlic cloves', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Low-sodium soy sauce', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '8', name: 'Sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
    ],
    instructions: [
      'Heat oil in wok on HIGH. Add garlic + white spring onion 30 sec.',
      'Push to side. Scramble eggs. Break into pieces.',
      'Add cold rice. Toss 3–4 min on HIGH.',
      'Add edamame and corn 2 min. Add soy + sesame. Toss.',
    ],
    tags: ['Vegetarian', 'Dinner'],
  },
  'VG-D6': {
    name: 'Tempeh Tacos with Mango Salsa & Chipotle Slaw',
    description: 'Tempeh tacos are the biggest trending vegetarian dinner across AU/NZ food media.',
    imageUrl: IMG + 'tempeh_tacos_with_mango_salsa_chipotle_slaw.png',
    blurhash: 'LFKd6r9GKjxE_Nxti_ofT|aeeSoz',
    cookTime: 22,
    prepTime: 5,
    servings: 2,
    calories: 640,
    ingredients: [
      { id: '1', name: 'Coles Organic Tempeh blocks, crumbled', quantity: '150', unit: 'g', category: 'pantry' },
      { id: '2', name: 'Olive oil + 2 tsp smoked paprika', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '3', name: 'Olive oil + 2 tsp cumin', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '4', name: 'Olive oil + 2 tsp garlic powder', quantity: '1', unit: 'tbsp', category: 'produce' },
      { id: '5', name: 'Olive oil + 2 tsp oregano', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: 'Soy sauce', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '7', name: 'Lime juice', quantity: '1', unit: 'tbsp', category: 'produce' },
      { id: '8', name: 'Small flour tortillas', quantity: '8', unit: 'whole', category: 'bakery' },
      { id: '9', name: 'MANGO SALSA: 1 ripe mango', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '10', name: 'Red onion', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Coriander', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '12', name: 'Lime', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '13', name: 'SLAW: 1 cup purple cabbage shredded', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '14', name: 'Chipotle mayo', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '15', name: 'Sliced avocado', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '16', name: 'Extra lime', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Crumble tempeh. Marinate in soy, lime and spices.',
      'Pan-fry in olive oil medium-high, 4–5 min undisturbed then toss 3 min.',
      'Make mango salsa and chipotle slaw.',
      'Warm tortillas 20 sec. Build tacos: slaw, tempeh, salsa, avocado, lime.',
    ],
    tags: ['Vegetarian', 'Dinner'],
  },
  'VG-D7': {
    name: 'Pumpkin, Sage & Parmesan Risotto',
    description: 'Australia\'s most-cooked vegetarian dinner across all demographics. The secret: hot stock added gradually + butter at the end.',
    imageUrl: IMG + 'pumpkin_sage_parmesan_risotto.png',
    blurhash: 'LVMQbN?a%$t8~qM{Rjj[catRVXt6',
    cookTime: 30,
    prepTime: 5,
    servings: 2,
    calories: 660,
    ingredients: [
      { id: '1', name: 'Arborio rice', quantity: '1', unit: 'cup', category: 'pantry' },
      { id: '2', name: 'Butternut pumpkin, cubed 1.5cm', quantity: '400', unit: 'g', category: 'dairy' },
      { id: '3', name: 'Warm veg stock', quantity: '1', unit: 'l', category: 'pantry' },
      { id: '4', name: 'Onion', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Garlic cloves', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Dry white wine', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '7', name: 'Parmesan grated', quantity: '40', unit: 'g', category: 'dairy' },
      { id: '8', name: 'Butter', quantity: '20', unit: 'g', category: 'dairy' },
      { id: '9', name: 'Fresh sage leaves', quantity: '8', unit: 'whole', category: 'pantry' },
      { id: '10', name: 'Black pepper', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '11', name: 'Nutmeg', quantity: '1', unit: 'whole', category: 'pantry' },
    ],
    instructions: [
      'Fry onion 3 min, garlic 1 min. Add pumpkin 3 min.',
      'Add rice, stir 1 min. Add wine, stir until absorbed.',
      'Add warm stock one ladle at a time, stirring each addition ~18–20 min total.',
      'Stir in butter and parmesan. Rest 2 min covered.',
      'Fry sage in butter 1 min until crisp. Serve topped with sage and extra parmesan.',
    ],
    tags: ['Vegetarian', 'Dinner'],
  },
  'VG-L1': {
    name: 'Roasted Capsicum, Tomato & Red Lentil Soup',
    description: 'Rich, vibrant soup. Roasting capsicum and tomatoes (15 min hands-off) makes the flavour.',
    imageUrl: IMG + 'roasted_capsicum_tomato_red_lentil_soup.png',
    blurhash: 'LDKT-.00.8NG~TspIVxZK*IARPxZ',
    cookTime: 25,
    prepTime: 5,
    servings: 2,
    calories: 420,
    ingredients: [
      { id: '1', name: 'Red capsicums, halved', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '2', name: 'Roma tomatoes, halved', quantity: '4', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Red lentils, rinsed', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '4', name: 'Small onion', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Garlic cloves', quantity: '2', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Cumin', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '7', name: 'Smoked paprika', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Low-sodium veg stock', quantity: '500', unit: 'ml', category: 'pantry' },
      { id: '9', name: 'Lemon juice', quantity: '1', unit: 'tbsp', category: 'produce' },
    ],
    instructions: [
      'Preheat oven 220C. Roast capsicum and tomatoes 15 min until blistered.',
      'Fry onion 3 min, garlic + spices 1 min. Add lentils + stock. Simmer 12 min.',
      'Add roasted veg. Blend smooth. Add lemon juice.',
    ],
    tags: ['Vegetarian', 'Lunch'],
  },
  'VG-L2': {
    name: 'Spinach & Ricotta Quesadillas with Tomato Salsa',
    description: 'Crispy golden quesadillas with creamy ricotta filling. 15 minutes.',
    imageUrl: IMG + 'spinach_ricotta_quesadillas_with_tomato_salsa.png',
    blurhash: 'LVL3_X_3xuxb~Vs:bIWVt.xaRjWA',
    cookTime: 15,
    prepTime: 5,
    servings: 2,
    calories: 490,
    ingredients: [
      { id: '1', name: 'Large flour tortillas', quantity: '4', unit: 'whole', category: 'bakery' },
      { id: '2', name: 'Fresh ricotta', quantity: '0.5', unit: 'cup', category: 'dairy' },
      { id: '3', name: 'Baby spinach, wilted', quantity: '2', unit: 'cups', category: 'produce' },
      { id: '4', name: 'Grated mozzarella or cheddar', quantity: '0.5', unit: 'cup', category: 'pantry' },
      { id: '5', name: 'Garlic powder', quantity: '0.25', unit: 'tsp', category: 'produce' },
      { id: '6', name: 'Pinch nutmeg', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '7', name: 'SALSA: 2 tomatoes', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Red onion', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '9', name: 'Coriander', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '10', name: 'Lime', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Wilt spinach, squeeze dry. Mix with ricotta, cheese, garlic, nutmeg.',
      'Spread on half of each tortilla. Fold in half.',
      'Cook in dry pan 2–3 min per side until golden.',
      'Make salsa. Serve alongside.',
    ],
    tags: ['Vegetarian', 'Lunch'],
  },
  'VG-L3': {
    name: 'Crispy Sesame Tofu Noodle Bowl with Edamame & Greens',
    description: 'Crispy golden tofu over noodles with soy-sesame dressing. Trending across AU/NZ.',
    imageUrl: IMG + 'crispy_sesame_tofu_noodle_bowl_with_edamame.png',
    blurhash: 'LSIqS^?G%Mxu_NNxRlW=KQxuRPoc',
    cookTime: 20,
    prepTime: 5,
    servings: 2,
    calories: 520,
    ingredients: [
      { id: '1', name: 'Extra-firm tofu , pressed, cubed', quantity: '300', unit: 'g', category: 'pantry' },
      { id: '2', name: 'Serves thin rice noodles or soba', quantity: '2', unit: 'whole', category: 'pantry' },
      { id: '3', name: 'Frozen edamame, microwaved 2 min', quantity: '1', unit: 'cup', category: 'frozen' },
      { id: '4', name: 'Baby spinach or bok choy', quantity: '2', unit: 'cups', category: 'produce' },
      { id: '5', name: 'Soy', quantity: '2', unit: 'tbsp', category: 'pantry' },
      { id: '6', name: 'Sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '7', name: 'Honey', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Garlic clove', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '9', name: 'Sesame seeds', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '10', name: 'Spring onion', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Lime', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Press tofu 5 min. Cube.',
      'Cook noodles per packet.',
      'Pan-fry tofu in oil on medium-high 3–4 min per side until golden.',
      'Make dressing. Toss noodles, edamame, spinach with dressing.',
      'Top with tofu, sesame seeds, spring onion. Squeeze lime.',
    ],
    tags: ['Vegetarian', 'Lunch'],
  },
  'VG-L4': {
    name: 'Leftover Tofu Bowl with Miso Dressing',
    description: 'Tuesday\'s crispy tofu with a miso dressing instead. Cold — completely different feel.',
    imageUrl: IMG + 'leftover_tofu_bowl_with_miso_dressing.png',
    blurhash: 'LJJ*I+~W%No#ksD*M{s,tSxtV?Rj',
    cookTime: 10,
    prepTime: 5,
    servings: 2,
    calories: 480,
    ingredients: [
      { id: '1', name: 'Leftover crispy tofu from Tuesday', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '2', name: 'Leftover rice noodles or baby spinach base', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '3', name: 'Lebanese cucumber, sliced', quantity: '0.5', unit: 'whole', category: 'produce' },
      { id: '4', name: 'Avocado per serve', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '5', name: 'MISO DRESSING: 1 tsp white miso', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '6', name: 'Rice wine vinegar', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '7', name: 'Sesame oil', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '8', name: 'Honey', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '9', name: 'Sesame seeds', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '10', name: 'Pickled ginger', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '11', name: 'Spring onion', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Make miso dressing: whisk all ingredients.',
      'Arrange base, cucumber, avocado, tofu.',
      'Drizzle dressing. Add pickled ginger and sesame seeds.',
    ],
    tags: ['Vegetarian', 'Lunch', 'Quick'],
  },
  'VG-L5': {
    name: 'Falafel Wraps with Hummus, Tabbouleh & Tahini',
    description: 'Falafel wraps are one of the most-ordered cafe lunches across Australia.',
    imageUrl: IMG + 'falafel_wraps_with_hummus_tabbouleh_tahini.png',
    blurhash: 'LIIXW[~V%Nt7rXM{R*aexbRkMxjY',
    cookTime: 20,
    prepTime: 5,
    servings: 2,
    calories: 530,
    ingredients: [
      { id: '1', name: 'Falafel', quantity: '8', unit: 'whole', category: 'pantry' },
      { id: '2', name: 'Wholegrain wraps or flatbreads', quantity: '4', unit: 'whole', category: 'bakery' },
      { id: '3', name: 'Hummus', quantity: '4', unit: 'tbsp', category: 'pantry' },
      { id: '4', name: 'Quick tabbouleh: 1/4 cup parsley', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Tomato', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Cucumber', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '7', name: 'Lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '8', name: 'Tahini sauce: 2 tbsp tahini', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '9', name: 'Lemon', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '10', name: 'Water', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '11', name: 'Shredded cos lettuce', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'If using mix: prepare per packet, pan-fry in olive oil 3 min per side.',
      'Assemble wraps: hummus, lettuce, tabbouleh, 4–5 falafel, tahini sauce.',
    ],
    tags: ['Vegetarian', 'Lunch'],
  },
  'VG-L6': {
    name: 'Leftover Coconut Dhal Tiffin Remix with Minted Yoghurt',
    description: 'Monday\'s coconut dhal reheated with quinoa and minted yoghurt. Flavours deepen overnight.',
    imageUrl: IMG + 'leftover_coconut_dhal_tiffin_fri_remix.png',
    blurhash: 'LHJ*P6~pXo-=.9IVi^t6KmWFs7Rj',
    cookTime: 10,
    prepTime: 5,
    servings: 2,
    calories: 500,
    ingredients: [
      { id: '1', name: 'Leftover coconut red lentil dhal', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '2', name: 'Cooked quinoa per serve', quantity: '0.75', unit: 'cup', category: 'pantry' },
      { id: '3', name: 'Plain yoghurt', quantity: '1', unit: 'tbsp', category: 'dairy' },
      { id: '4', name: 'Dried mint', quantity: '1', unit: 'tsp', category: 'pantry' },
      { id: '5', name: 'Fresh coriander', quantity: '1', unit: 'whole', category: 'produce' },
      { id: '6', name: 'Cherry tomatoes', quantity: '0.25', unit: 'cup', category: 'produce' },
      { id: '7', name: 'Lime wedge', quantity: '1', unit: 'whole', category: 'produce' },
    ],
    instructions: [
      'Reheat dhal 2 min. Add splash of water if too thick.',
      'Make minted yoghurt: stir yoghurt and mint.',
      'Serve dhal over quinoa. Top with yoghurt, coriander, tomatoes. Squeeze lime.',
    ],
    tags: ['Vegetarian', 'Lunch', 'Quick'],
  },
  'VG-L7': {
    name: 'Halloumi & Watermelon Salad with Mint & Chilli',
    description: 'Most searched and shared vegetarian recipe in Australia during summer. Sweet + salty.',
    imageUrl: IMG + 'halloumi_watermelon_salad_with_mint_chilli.png',
    blurhash: 'LNK1Xg~qt--;~qayM{j[5oxve8Ri',
    cookTime: 18,
    prepTime: 5,
    servings: 2,
    calories: 480,
    ingredients: [
      { id: '1', name: 'Halloumi , sliced 1cm', quantity: '250', unit: 'g', category: 'dairy' },
      { id: '2', name: 'Seedless watermelon, cubed', quantity: '2', unit: 'cups', category: 'pantry' },
      { id: '3', name: 'Rocket', quantity: '2', unit: 'handfuls', category: 'produce' },
      { id: '4', name: 'Red onion, sliced', quantity: '0.25', unit: 'whole', category: 'produce' },
      { id: '5', name: 'Small handful fresh mint leaves', quantity: '1', unit: 'whole', category: 'pantry' },
      { id: '6', name: 'Chilli flakes', quantity: '0.5', unit: 'tsp', category: 'produce' },
      { id: '7', name: 'Olive oil', quantity: '1', unit: 'tbsp', category: 'pantry' },
      { id: '8', name: 'Lemon juice', quantity: '1', unit: 'tbsp', category: 'produce' },
    ],
    instructions: [
      'Heat dry non-stick pan or grill pan on HIGH.',
      'Cook halloumi 2 min per side until deeply golden.',
      'Arrange rocket, watermelon, red onion on plates.',
      'Lay halloumi over. Scatter mint and chilli. Drizzle oil and lemon.',
    ],
    tags: ['Vegetarian', 'Lunch'],
  },
};

// ── No-cook placeholders (recipe-less labelled slots) ──
const GRAB_GO_BREAKFAST: CuratedRecipe = {
  name: 'Grab & go',
  description:
    'No cooking — grab a quick option on your way out: Greek yoghurt, fruit and nuts, a smoothie or a muesli bar.',
  imageUrl: IMG + 'greek_yoghurt_parfait_with_granola_strawberries.png',
  blurhash: 'L8HL3l~V01I;57D%9GM{9uR+^i-p',
  cookTime: 0, prepTime: 0, servings: 2, calories: 0,
  ingredients: [], instructions: [], tags: ['Grab & Go', 'No Cook'],
};
const BUY_OUT_LUNCH: CuratedRecipe = {
  name: 'Buy out',
  description: 'No cooking — pick up a lunch out. Aim for a veg-forward option to stay on track.',
  imageUrl: IMG + 'greek_yoghurt_parfait_with_granola_strawberries.png',
  blurhash: 'L8HL3l~V01I;57D%9GM{9uR+^i-p',
  cookTime: 0, prepTime: 0, servings: 2, calories: 0,
  ingredients: [], instructions: [], tags: ['Buy Out', 'No Cook'],
};
const BUY_OUT_DINNER: CuratedRecipe = {
  ...BUY_OUT_LUNCH,
  description: 'No cooking tonight — buy dinner out or order in. No groceries needed for this slot.',
};

// ── Pools the engine draws from ──
const VEGETARIAN_BANK: PlanBank = {
  recipes: RECIPES,
  breakfastWeekendCook: ['VG-B1', 'VG-B4', 'VG-B7'], // hot/cooked breakfasts (weekends)
  breakfastWeekdayEasy: ['VG-B2', 'VG-B3', 'VG-B5', 'VG-B6'], // no-cook breakfasts (weekdays)
  lunchCook: ['VG-L1', 'VG-L2', 'VG-L3', 'VG-L5', 'VG-L7', 'VG-L1', 'VG-L2'],
  dinnersFresh: ['VG-D1', 'VG-D2', 'VG-D3', 'VG-D4', 'VG-D5', 'VG-D6', 'VG-D7'],
  batchMains: ['VG-D1', 'VG-D2', 'VG-D3', 'VG-D4', 'VG-D5', 'VG-D6', 'VG-D7', 'VG-L1', 'VG-L2', 'VG-L3', 'VG-L5', 'VG-L7'],
  grabGoBreakfast: GRAB_GO_BREAKFAST,
  buyOutLunch: BUY_OUT_LUNCH,
  buyOutDinner: BUY_OUT_DINNER,
};

// Distinct mains available to batch-cook (ceiling for "recipes each cook day").
export const VEGETARIAN_MAX_BATCH_RECIPES = VEGETARIAN_BANK.batchMains.length;

export function buildVegetarianMeals(
  durationDays: number,
  prefs: CookingPreferences = DEFAULT_COOKING_PREFS,
  startWeekday: number = 0,
): ScheduledMeal[] {
  return buildPlanMeals(VEGETARIAN_BANK, durationDays, prefs, startWeekday);
}
